SCALE Job started on Tue 10/07/2018 09:38:17
With Host name andrei2-HP-Notebook
working directory /tmp/scale.andrei2.5109
and process id 5109.
Input file named /home/andrei2/Desktop/ornl/msfr/scale/gas_removal/temp/opus_print.inp
and output file named /home/andrei2/Desktop/ornl/msfr/scale/gas_removal/temp/opus_print.out
##########################################################
cp /home/andrei2/Desktop/ornl/msfr/scale/gas_removal/msfr_unit_vol_gases_removal.f71 f71
