SCALE Job started on Tue 19/06/2018 08:57:45
With Host name andrei2-HP-Notebook
working directory /tmp/scale.andrei2.1089
and process id 1089.
Input file named /home/andrei2/Desktop/ornl/rebus/scale/rebus_quarter_cell2.inp
and output file named /home/andrei2/Desktop/ornl/rebus/scale/rebus_quarter_cell2.out
##########################################################
>>> Loading SCALE Standard Composition Library from /home/andrei2/SCALE/SCALE-6.2.3/data/scale.rev39.sclib
>>> Loading CE library /home/andrei2/SCALE/SCALE-6.2.3/data/ce_v7.0_endf.xml
 ===================================================================================================================================
   Outer iteration sweep begins 06/ 19/ 2018 at 08:58:30

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.97128   3.205E-03 7.816E-01 (    3,185)   1.000E+00 (    1,  0) 08:58:34    4.0 s     4.0 s 100.8%    F
     2    0.97022   1.098E-03 7.028E-02 (    4,  1)   4.053E-01 (  915,  0) 08:58:38    7.9 s     3.9 s  97.0%    F
     3    0.97019   2.742E-05 4.702E-02 (    3,230)   7.412E-02 (    1,  0) 08:58:41   11.7 s     3.8 s 126.3%    F
     4    0.97020   8.424E-06 1.778E-02 (    3, 59)   1.511E-02 (   65,  0) 08:58:45   15.4 s     3.7 s  92.5%    F
     5    0.97018   2.302E-05 9.548E-03 (    4,214)   6.297E-03 (   65,  0) 08:58:49   19.8 s     4.4 s 110.0%    F
     6    0.97001   1.785E-04 4.987E-03 (    4,228)   3.193E-03 (   65,  0) 08:58:55   25.6 s     5.8 s  96.0%    F
     7    0.96951   5.110E-04 2.940E-03 (    3, 81)   1.684E-03 (   65,  0) 08:59:05   35.0 s     9.4 s  94.4%    F
     8    0.96935   1.687E-04 1.825E-03 (    3, 81)   1.405E-03 (  627,  0) 08:59:12   42.6 s     7.6 s 108.7%    F
     9    0.96929   5.345E-05 8.747E-04 (    3, 81)   7.549E-04 (  882,  0) 08:59:19   49.4 s     6.8 s  97.1%    F
    10    0.96928   1.983E-05 4.628E-04 (    3, 81)   3.706E-04 (  915,  0) 08:59:26   56.2 s     6.7 s  96.3%    F
 k-eff =       0.96927509     


  Time per Iteration (sec):
 Transport Sweeping:     2.819
 Inscatter Source  :     0.534
 Coarse-Mesh Accel :     3.228
 Else (Convergence):     0.325
 Total (per outer):      6.906

  Total iteration time breakdown (sec):
 Transport Sweeping:    28.195
 Inscatter Source  :     5.337
 Coarse-Mesh Accel :    32.276
 Else (Convergence):     3.254
 Total Time        :    69.062

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.69276E-01
 Equivalent core height is infinite.
The number of cross section groups is 0, but the number of flux groups is 238 in Malocs.
