SCALE Job started on Mon 02/07/2018 08:06:14
With Host name andrei2-HP-Notebook
working directory /tmp/scale.andrei2.32143
and process id 32143.
Input file named /home/andrei2/Desktop/ornl/mcsfr/scale/no_reproc_depl/510efpd/quarter_cell.inp
and output file named /home/andrei2/Desktop/ornl/mcsfr/scale/no_reproc_depl/510efpd/quarter_cell.out
##########################################################
>>> Loading SCALE Standard Composition Library from /home/andrei2/SCALE/SCALE-6.2.3/data/scale.rev39.sclib
>>> Loading CE library /home/andrei2/SCALE/SCALE-6.2.3/data/ce_v7.0_endf.xml
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 02/ 2018 at 08:10:07

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.00268   6.732E-03 4.338E+00 (    3,137)   1.000E+00 (    1,  0) 08:10:10    3.6 s     3.6 s 119.0%    F
     2    1.00130   1.383E-03 1.643E-01 (    4,  1)   6.625E-01 ( 1084,  0) 08:10:14    6.9 s     3.3 s  83.3%    F
     3    1.00140   9.564E-05 3.870E-02 (    4,  9)   1.129E-01 (    4,  0) 08:10:17   10.1 s     3.2 s 105.0%    F
     4    1.00146   6.511E-05 2.722E-02 (    3,228)   2.255E-02 (  101,  0) 08:10:21   13.8 s     3.8 s  94.2%    F
     5    1.00144   1.748E-05 5.399E-03 (    3, 56)   1.678E-02 ( 1084,  0) 08:10:25   18.4 s     4.6 s 114.0%    F
     6    1.00137   6.870E-05 3.185E-03 (    3, 57)   1.484E-02 ( 1084,  0) 08:10:30   23.3 s     5.0 s  99.2%    F
     7    1.00115   2.209E-04 2.523E-03 (    2, 73)   1.138E-02 ( 1084,  0) 08:10:37   29.8 s     6.5 s  92.1%    F
     8    1.00092   2.330E-04 1.246E-03 (    4, 63)   8.722E-03 ( 1083,  0) 08:10:44   37.1 s     7.3 s 104.1%    F
     9    1.00084   8.267E-05 9.067E-04 (    4,202)   6.389E-03 ( 1050,  0) 08:10:50   43.5 s     6.4 s 107.0%    F
    10    1.00081   2.988E-05 4.949E-04 (    4,142)   4.278E-03 ( 1050,  0) 08:10:56   48.7 s     5.2 s  87.0%    F
    11    1.00079   1.661E-05 4.402E-04 (    4,228)   2.861E-03 ( 1050,  0) 08:11:00   53.6 s     4.9 s 121.5%    F
    12    1.00078   1.080E-05 3.818E-04 (    4,228)   1.957E-03 ( 1050,  0) 08:11:06   58.8 s     5.2 s  87.5%    F
    13    1.00077   6.730E-06 2.730E-04 (    4,228)   1.348E-03 ( 1050,  0) 08:11:11   64.5 s     5.7 s 113.4%    F
    14    1.00077   4.515E-06 1.938E-04 (    4,228)   9.090E-04 ( 1050,  0) 08:11:17   70.3 s     5.8 s  97.5%    F
    15    1.00077   2.761E-06 1.332E-04 (    4,228)   6.189E-04 (  984,  0) 08:11:23   76.0 s     5.7 s  94.8%    F
 k-eff =       1.00076588     Collapsing solution


  Time per Iteration (sec):
 Transport Sweeping:     2.552
 Inscatter Source  :     0.457
 Coarse-Mesh Accel :     2.658
 Else (Convergence):     0.206
 Total (per outer):      5.873

  Total iteration time breakdown (sec):
 Transport Sweeping:    38.284
 Inscatter Source  :     6.850
 Coarse-Mesh Accel :    39.876
 Else (Convergence):     3.084
 Total Time        :    88.094

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.00075E+00
 Equivalent core height is infinite.
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1019  for Nuclide:       94237
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1020  for Nuclide:       94237
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1019  for Nuclide:       94244
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1020  for Nuclide:       94244
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1019  for Nuclide:       96241
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1019  for Nuclide:       96248
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1020  for Nuclide:       96248
>>> Loading CE library /home/andrei2/SCALE/SCALE-6.2.3/data/ce_v7.0_endf.xml
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 02/ 2018 at 08:15:32

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.01287   8.939E-03 4.676E-01 (    2, 21)   1.000E+00 (    1,  0) 08:15:33    0.9 s     0.9 s  95.0%    F
     2    1.01211   7.439E-04 1.521E-01 (    4,  3)   6.691E-01 ( 1084,  0) 08:15:34    1.8 s     0.8 s  85.0%    F
     3    1.01193   1.839E-04 3.757E-02 (    4,  3)   1.111E-01 (    4,  0) 08:15:35    2.7 s     0.9 s  93.0%    F
     4    1.01187   6.177E-05 1.311E-02 (    3, 22)   3.023E-02 ( 1084,  0) 08:15:36    3.7 s     0.9 s  93.0%    F
     5    1.01180   6.525E-05 7.941E-03 (    3, 22)   2.100E-02 ( 1084,  0) 08:15:37    4.5 s     0.8 s  81.0%    F
     6    1.01173   6.413E-05 4.830E-03 (    3, 22)   1.555E-02 ( 1050,  0) 08:15:38    5.2 s     0.8 s  77.0%    F
     7    1.01168   4.923E-05 3.090E-03 (    3, 22)   1.133E-02 ( 1050,  0) 08:15:38    6.0 s     0.8 s  76.0%    F
     8    1.01162   6.555E-05 2.057E-03 (    2, 22)   8.238E-03 ( 1050,  0) 08:15:39    6.8 s     0.8 s  80.0%    F
     9    1.01155   6.950E-05 1.318E-03 (    3, 22)   6.173E-03 ( 1050,  0) 08:15:40    7.6 s     0.8 s  83.0%    F
    10    1.01150   4.948E-05 8.882E-04 (    3, 22)   4.415E-03 ( 1050,  0) 08:15:41    8.4 s     0.8 s  81.0%    F
    11    1.01146   3.299E-05 5.989E-04 (    3, 22)   3.133E-03 ( 1050,  0) 08:15:42    9.3 s     0.8 s  83.0%    F
    12    1.01144   2.209E-05 3.934E-04 (    3, 22)   2.219E-03 ( 1050,  0) 08:15:43   10.2 s     0.9 s  91.0%    F
    13    1.01143   1.409E-05 2.593E-04 (    3, 22)   1.574E-03 (  984,  0) 08:15:44   11.1 s     0.9 s  87.0%    F
    14    1.01142   1.161E-05 1.886E-04 (    2, 22)   1.138E-03 ( 1048,  0) 08:15:44   11.9 s     0.9 s  87.0%    F
    15    1.01141   8.974E-06 1.404E-04 (    2, 47)   8.327E-04 ( 1048,  0) 08:15:45   12.8 s     0.9 s  89.0%    F
    16    1.01140   4.934E-06 8.900E-05 (    3, 48)   6.022E-04 ( 1048,  0) 08:15:46   13.7 s     0.9 s  86.0%    F
 k-eff =       1.01140194     Time=      0.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.643
 Inscatter Source  :     0.095
 Coarse-Mesh Accel :     0.237
 Else (Convergence):     0.044
 Total (per outer):      1.019

  Total iteration time breakdown (sec):
 Transport Sweeping:    10.290
 Inscatter Source  :     1.513
 Coarse-Mesh Accel :     3.789
 Else (Convergence):     0.712
 Total Time        :    16.304

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.01139E+00
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 02/ 2018 at 08:16:22

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.01047   1.803E-04 7.362E-02 (    2, 29)   1.420E-01 (    6,  0) 08:16:23    1.0 s     1.0 s 104.0%    F
     2    1.01037   9.724E-05 4.277E-03 (    2, 46)   2.262E-03 (  235,  0) 08:16:24    2.1 s     1.0 s 104.0%    F
     3    1.01033   3.755E-05 9.147E-04 (    3, 43)   3.596E-04 (    3,  0) 08:16:25    3.1 s     1.0 s 104.0%    F
     4    1.01032   1.264E-05 2.269E-04 (    3, 46)   3.045E-04 (    3,  0) 08:16:26    4.2 s     1.0 s 104.0%    F
 k-eff =       1.01032015     Time=     15.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.602
 Inscatter Source  :     0.091
 Coarse-Mesh Accel :     0.591
 Else (Convergence):     0.174
 Total (per outer):      1.457

  Total iteration time breakdown (sec):
 Transport Sweeping:     2.409
 Inscatter Source  :     0.362
 Coarse-Mesh Accel :     2.364
 Else (Convergence):     0.695
 Total Time        :     5.830

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.01031E+00
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 02/ 2018 at 08:17:01

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.01048   3.141E-04 9.750E-02 (    3, 35)   1.459E-01 ( 1064,  0) 08:17:02    1.0 s     1.0 s 104.0%    F
     2    1.01037   1.086E-04 5.761E-03 (    3, 40)   3.529E-03 ( 1027,  0) 08:17:03    2.1 s     1.0 s 105.0%    F
     3    1.01033   4.360E-05 1.066E-03 (    3, 41)   7.424E-04 (    3,  0) 08:17:04    3.1 s     1.0 s 104.0%    F
     4    1.01031   1.679E-05 2.349E-04 (    3, 42)   4.180E-04 (    3,  0) 08:17:05    4.2 s     1.0 s 105.0%    F
 k-eff =       1.01031330     Time=     45.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.602
 Inscatter Source  :     0.091
 Coarse-Mesh Accel :     0.672
 Else (Convergence):     0.172
 Total (per outer):      1.537

  Total iteration time breakdown (sec):
 Transport Sweeping:     2.409
 Inscatter Source  :     0.363
 Coarse-Mesh Accel :     2.690
 Else (Convergence):     0.687
 Total Time        :     6.149

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.01031E+00
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 02/ 2018 at 08:17:41

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.00985   1.853E-06 7.713E-02 (    3, 35)   1.237E-01 ( 1064,  0) 08:17:42    1.0 s     1.0 s 104.0%    F
     2    1.00984   1.643E-05 2.761E-03 (    3, 39)   3.624E-03 (  371,  0) 08:17:43    2.1 s     1.0 s 104.0%    F
     3    1.00982   1.517E-05 4.832E-04 (    4, 47)   8.240E-04 (   31,  0) 08:17:45    3.1 s     1.0 s  52.0%    F
     4    1.00981   8.753E-06 2.094E-04 (    3, 18)   3.419E-04 (  408,  0) 08:17:46    4.2 s     1.1 s 108.0%    F
 k-eff =       1.00981390     Time=     75.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.608
 Inscatter Source  :     0.094
 Coarse-Mesh Accel :     0.693
 Else (Convergence):     0.173
 Total (per outer):      1.568

  Total iteration time breakdown (sec):
 Transport Sweeping:     2.433
 Inscatter Source  :     0.376
 Coarse-Mesh Accel :     2.772
 Else (Convergence):     0.690
 Total Time        :     6.271

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.00982E+00
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 02/ 2018 at 08:18:23

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.00938   1.662E-05 6.705E-02 (    3, 35)   1.080E-01 ( 1064,  0) 08:18:24    1.1 s     1.1 s 107.0%    F
     2    1.00937   1.570E-05 1.794E-03 (    3, 36)   3.230E-03 (  303,  0) 08:18:25    2.1 s     1.1 s 107.0%    F
     3    1.00935   1.516E-05 4.108E-04 (    4, 47)   6.846E-04 (   31,  0) 08:18:26    3.2 s     1.1 s 110.0%    F
     4    1.00934   8.788E-06 1.970E-04 (    3, 18)   2.736E-04 (   35,  0) 08:18:27    4.4 s     1.2 s 118.0%    F
 k-eff =       1.00934145     Time=    105.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.634
 Inscatter Source  :     0.097
 Coarse-Mesh Accel :     0.594
 Else (Convergence):     0.175
 Total (per outer):      1.499

  Total iteration time breakdown (sec):
 Transport Sweeping:     2.537
 Inscatter Source  :     0.386
 Coarse-Mesh Accel :     2.375
 Else (Convergence):     0.699
 Total Time        :     5.997

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.00934E+00
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 02/ 2018 at 08:19:05

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.00892   1.455E-05 5.950E-02 (    3, 35)   9.557E-02 ( 1064,  0) 08:19:06    1.0 s     1.0 s 104.0%    F
     2    1.00891   1.524E-05 1.339E-03 (    3, 34)   2.957E-03 ( 1027,  0) 08:19:07    2.1 s     1.1 s 106.0%    F
     3    1.00889   1.502E-05 3.799E-04 (    4, 47)   6.399E-04 (  476,  0) 08:19:08    3.2 s     1.1 s 106.0%    F
     4    1.00888   8.737E-06 1.683E-04 (    3, 18)   2.521E-04 (    3,  0) 08:19:09    4.2 s     1.1 s 108.0%    F
 k-eff =       1.00888160     Time=    135.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.617
 Inscatter Source  :     0.095
 Coarse-Mesh Accel :     0.543
 Else (Convergence):     0.173
 Total (per outer):      1.428

  Total iteration time breakdown (sec):
 Transport Sweeping:     2.467
 Inscatter Source  :     0.380
 Coarse-Mesh Accel :     2.172
 Else (Convergence):     0.693
 Total Time        :     5.712

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.00888E+00
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 02/ 2018 at 08:19:48

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.00845   4.249E-06 5.334E-02 (    3, 35)   8.563E-02 ( 1064,  0) 08:19:49    1.1 s     1.1 s 114.0%    F
     2    1.00843   1.621E-05 1.096E-03 (    4, 47)   2.763E-03 ( 1027,  0) 08:19:50    2.2 s     1.1 s 109.0%    F
     3    1.00842   1.559E-05 3.596E-04 (    4, 47)   6.190E-04 (  476,  0) 08:19:51    3.3 s     1.0 s 104.0%    F
     4    1.00841   8.804E-06 1.678E-04 (    3, 18)   2.398E-04 (   35,  0) 08:19:52    4.3 s     1.1 s 105.0%    F
 k-eff =       1.00841019     Time=    165.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.625
 Inscatter Source  :     0.096
 Coarse-Mesh Accel :     0.554
 Else (Convergence):     0.191
 Total (per outer):      1.465

  Total iteration time breakdown (sec):
 Transport Sweeping:     2.499
 Inscatter Source  :     0.383
 Coarse-Mesh Accel :     2.215
 Else (Convergence):     0.762
 Total Time        :     5.859

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.00836E+00
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 02/ 2018 at 08:20:29

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.00806   5.826E-05 5.040E-02 (    3, 35)   7.750E-02 ( 1064,  0) 08:20:30    1.0 s     1.0 s  97.0%    F
     2    1.00804   2.691E-05 1.373E-03 (    3, 33)   2.823E-03 (   98,  0) 08:20:31    2.0 s     1.0 s 100.0%    F
     3    1.00802   2.059E-05 5.444E-04 (    3, 14)   6.653E-04 (    3,  0) 08:20:32    3.0 s     1.0 s  98.0%    F
     4    1.00801   1.083E-05 2.814E-04 (    3, 14)   3.631E-04 (    3,  0) 08:20:33    4.0 s     1.0 s 100.0%    F
 k-eff =       1.00800549     Time=    195.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.563
 Inscatter Source  :     0.088
 Coarse-Mesh Accel :     0.545
 Else (Convergence):     0.168
 Total (per outer):      1.364

  Total iteration time breakdown (sec):
 Transport Sweeping:     2.254
 Inscatter Source  :     0.351
 Coarse-Mesh Accel :     2.182
 Else (Convergence):     0.671
 Total Time        :     5.458

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.00797E+00
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 02/ 2018 at 08:21:09

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.00758   1.515E-05 4.463E-02 (    3, 35)   7.062E-02 ( 1064,  0) 08:21:10    1.0 s     1.0 s  97.0%    F
     2    1.00757   1.646E-05 9.927E-04 (    4, 47)   2.386E-03 (  371,  0) 08:21:11    1.9 s     1.0 s  97.0%    F
     3    1.00755   1.549E-05 3.308E-04 (    4, 45)   6.308E-04 ( 1019,  0) 08:21:12    3.0 s     1.0 s 103.0%    F
     4    1.00754   8.936E-06 1.456E-04 (    4, 45)   2.828E-04 (   64,  0) 08:21:13    4.0 s     1.0 s 105.0%    F
 k-eff =       1.00754318     Time=    225.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.573
 Inscatter Source  :     0.090
 Coarse-Mesh Accel :     0.499
 Else (Convergence):     0.170
 Total (per outer):      1.332

  Total iteration time breakdown (sec):
 Transport Sweeping:     2.291
 Inscatter Source  :     0.361
 Coarse-Mesh Accel :     1.998
 Else (Convergence):     0.678
 Total Time        :     5.328

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.00753E+00
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 02/ 2018 at 08:21:54

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.00713   1.472E-05 4.283E-02 (    3, 49)   6.476E-02 ( 1064,  0) 08:21:56    1.2 s     1.2 s  58.0%    F
     2    1.00711   1.626E-05 9.699E-04 (    4, 45)   2.245E-03 ( 1027,  0) 08:21:57    2.4 s     1.2 s 120.0%    F
     3    1.00710   1.524E-05 3.289E-04 (    4, 45)   5.747E-04 ( 1050,  0) 08:21:58    3.5 s     1.2 s 119.0%    F
     4    1.00709   8.744E-06 1.460E-04 (    4, 45)   2.414E-04 ( 1050,  0) 08:21:59    4.7 s     1.1 s 112.0%    F
 k-eff =       1.00708732     Time=    255.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.686
 Inscatter Source  :     0.106
 Coarse-Mesh Accel :     0.718
 Else (Convergence):     0.200
 Total (per outer):      1.710

  Total iteration time breakdown (sec):
 Transport Sweeping:     2.744
 Inscatter Source  :     0.425
 Coarse-Mesh Accel :     2.871
 Else (Convergence):     0.800
 Total Time        :     6.840

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.00712E+00
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 02/ 2018 at 08:22:45

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.00668   1.417E-05 3.802E-02 (    3, 35)   5.980E-02 ( 1064,  0) 08:22:47    1.5 s     1.5 s  76.5%    F
     2    1.00666   1.609E-05 9.642E-04 (    3, 49)   2.131E-03 ( 1100,  0) 08:22:48    3.0 s     1.5 s 151.0%    F
     3    1.00665   1.510E-05 3.216E-04 (    3, 49)   5.589E-04 (  476,  0) 08:22:50    4.6 s     1.5 s  76.0%    F
     4    1.00664   8.643E-06 1.402E-04 (    4, 43)   2.265E-04 ( 1050,  0) 08:22:51    6.1 s     1.6 s 155.0%    F
 k-eff =       1.00663939     Time=    285.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.881
 Inscatter Source  :     0.139
 Coarse-Mesh Accel :     0.763
 Else (Convergence):     0.231
 Total (per outer):      2.014

  Total iteration time breakdown (sec):
 Transport Sweeping:     3.525
 Inscatter Source  :     0.554
 Coarse-Mesh Accel :     3.054
 Else (Convergence):     0.925
 Total Time        :     8.058

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.00666E+00
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 02/ 2018 at 08:23:34

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.00624   1.268E-05 3.531E-02 (    3, 35)   5.546E-02 ( 1064,  0) 08:23:35    1.1 s     1.1 s 107.0%    F
     2    1.00623   1.563E-05 1.040E-03 (    3, 49)   2.076E-03 ( 1131,  0) 08:23:36    2.2 s     1.1 s 108.0%    F
     3    1.00621   1.488E-05 3.328E-04 (    3, 49)   5.467E-04 (  476,  0) 08:23:37    3.2 s     1.1 s 108.0%    F
     4    1.00620   8.547E-06 1.352E-04 (    4, 43)   2.209E-04 ( 1050,  0) 08:23:38    4.3 s     1.1 s 106.0%    F
 k-eff =       1.00620234     Time=    315.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.618
 Inscatter Source  :     0.095
 Coarse-Mesh Accel :     0.506
 Else (Convergence):     0.169
 Total (per outer):      1.388

  Total iteration time breakdown (sec):
 Transport Sweeping:     2.473
 Inscatter Source  :     0.378
 Coarse-Mesh Accel :     2.025
 Else (Convergence):     0.676
 Total Time        :     5.552

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.00619E+00
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 02/ 2018 at 08:24:15

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.00581   1.339E-05 3.447E-02 (    3, 49)   5.167E-02 ( 1064,  0) 08:24:16    1.0 s     1.0 s  97.0%    F
     2    1.00579   1.589E-05 1.118E-03 (    3, 49)   2.020E-03 ( 1131,  0) 08:24:17    1.9 s     1.0 s  97.0%    F
     3    1.00578   1.491E-05 3.381E-04 (    3, 49)   5.330E-04 (  476,  0) 08:24:18    2.9 s     1.0 s  99.0%    F
     4    1.00577   8.522E-06 1.307E-04 (    4, 42)   2.170E-04 ( 1050,  0) 08:24:19    3.9 s     1.0 s  99.0%    F
 k-eff =       1.00576645     Time=    345.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.563
 Inscatter Source  :     0.088
 Coarse-Mesh Accel :     0.579
 Else (Convergence):     0.168
 Total (per outer):      1.398

  Total iteration time breakdown (sec):
 Transport Sweeping:     2.252
 Inscatter Source  :     0.350
 Coarse-Mesh Accel :     2.318
 Else (Convergence):     0.671
 Total Time        :     5.591

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.00576E+00
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 02/ 2018 at 08:24:59

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.00537   1.283E-05 3.080E-02 (    3, 35)   4.831E-02 ( 1064,  0) 08:25:00    1.0 s     1.0 s  98.0%    F
     2    1.00536   1.581E-05 1.165E-03 (    3, 49)   1.971E-03 ( 1131,  0) 08:25:01    2.0 s     1.0 s 105.0%    F
     3    1.00534   1.486E-05 3.425E-04 (    3, 49)   5.211E-04 (  476,  0) 08:25:02    3.1 s     1.1 s 110.0%    F
     4    1.00533   8.496E-06 1.268E-04 (    3, 47)   2.136E-04 ( 1019,  0) 08:25:03    4.4 s     1.3 s 131.0%    F
 k-eff =       1.00533349     Time=    375.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.625
 Inscatter Source  :     0.101
 Coarse-Mesh Accel :     0.776
 Else (Convergence):     0.171
 Total (per outer):      1.673

  Total iteration time breakdown (sec):
 Transport Sweeping:     2.502
 Inscatter Source  :     0.403
 Coarse-Mesh Accel :     3.104
 Else (Convergence):     0.685
 Total Time        :     6.694

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.00533E+00
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 02/ 2018 at 08:25:45

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.00494   1.218E-05 2.888E-02 (    3, 35)   4.536E-02 (  440,  0) 08:25:46    1.0 s     1.0 s 103.0%    F
     2    1.00492   1.621E-05 1.182E-03 (    3, 49)   1.928E-03 ( 1100,  0) 08:25:47    2.2 s     1.2 s 117.0%    F
     3    1.00491   1.496E-05 3.409E-04 (    3, 49)   5.076E-04 ( 1050,  0) 08:25:48    3.3 s     1.1 s 113.0%    F
     4    1.00490   8.493E-06 1.262E-04 (    3, 47)   2.091E-04 (   64,  0) 08:25:49    4.5 s     1.2 s 117.0%    F
 k-eff =       1.00489890     Time=    405.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.646
 Inscatter Source  :     0.104
 Coarse-Mesh Accel :     0.549
 Else (Convergence):     0.185
 Total (per outer):      1.484

  Total iteration time breakdown (sec):
 Transport Sweeping:     2.586
 Inscatter Source  :     0.415
 Coarse-Mesh Accel :     2.197
 Else (Convergence):     0.740
 Total Time        :     5.938

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.00489E+00
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 02/ 2018 at 08:26:27

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.00452   1.200E-05 3.489E-02 (    3, 49)   4.269E-02 ( 1064,  0) 08:26:28    1.0 s     1.0 s  97.0%    F
     2    1.00450   1.571E-05 1.247E-03 (    3, 49)   1.880E-03 ( 1131,  0) 08:26:29    2.0 s     1.0 s  98.0%    F
     3    1.00448   1.473E-05 3.417E-04 (    3, 49)   5.009E-04 ( 1050,  0) 08:26:30    2.9 s     1.0 s  97.0%    F
     4    1.00448   8.408E-06 1.261E-04 (    3, 47)   2.064E-04 (   64,  0) 08:26:31    3.9 s     1.0 s  99.0%    F
 k-eff =       1.00447599     Time=    435.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.562
 Inscatter Source  :     0.087
 Coarse-Mesh Accel :     0.570
 Else (Convergence):     0.168
 Total (per outer):      1.387

  Total iteration time breakdown (sec):
 Transport Sweeping:     2.247
 Inscatter Source  :     0.348
 Coarse-Mesh Accel :     2.280
 Else (Convergence):     0.673
 Total Time        :     5.548

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.00448E+00
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 02/ 2018 at 08:27:12

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.00410   1.118E-05 2.728E-02 (    3, 49)   4.030E-02 ( 1064,  0) 08:27:13    1.1 s     1.1 s 110.0%    F
     2    1.00408   1.541E-05 1.255E-03 (    3, 49)   1.840E-03 ( 1100,  0) 08:27:14    2.2 s     1.1 s 115.0%    F
     3    1.00407   1.459E-05 3.393E-04 (    3, 49)   4.930E-04 ( 1050,  0) 08:27:15    3.3 s     1.0 s 102.0%    F
     4    1.00406   8.351E-06 1.255E-04 (    3, 47)   2.031E-04 ( 1019,  0) 08:27:17    4.5 s     1.3 s  63.0%    F
 k-eff =       1.00405789     Time=    465.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.646
 Inscatter Source  :     0.102
 Coarse-Mesh Accel :     0.637
 Else (Convergence):     0.217
 Total (per outer):      1.602

  Total iteration time breakdown (sec):
 Transport Sweeping:     2.583
 Inscatter Source  :     0.409
 Coarse-Mesh Accel :     2.547
 Else (Convergence):     0.869
 Total Time        :     6.408

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.00404E+00
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 02/ 2018 at 08:28:01

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.00368   1.084E-05 2.660E-02 (    3, 49)   3.814E-02 ( 1064,  0) 08:28:03    1.2 s     1.2 s  58.0%    F
     2    1.00367   1.532E-05 1.257E-03 (    3, 49)   1.798E-03 ( 1100,  0) 08:28:04    2.1 s     1.0 s  98.0%    F
     3    1.00365   1.452E-05 3.353E-04 (    3, 49)   4.850E-04 ( 1050,  0) 08:28:05    3.1 s     1.0 s  97.0%    F
     4    1.00365   8.311E-06 1.240E-04 (    3, 47)   1.996E-04 ( 1019,  0) 08:28:06    4.1 s     1.0 s 100.0%    F
 k-eff =       1.00364562     Time=    495.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.588
 Inscatter Source  :     0.093
 Coarse-Mesh Accel :     0.665
 Else (Convergence):     0.209
 Total (per outer):      1.554

  Total iteration time breakdown (sec):
 Transport Sweeping:     2.351
 Inscatter Source  :     0.370
 Coarse-Mesh Accel :     2.660
 Else (Convergence):     0.836
 Total Time        :     6.217

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.00365E+00
 Equivalent core height is infinite.
