SCALE Job started on Tue 24/07/2018 11:34:31
With Host name andrei2-HP-Notebook
working directory /tmp/scale.andrei2.24290
and process id 24290.
Input file named /home/andrei2/Desktop/ornl/msfr/scale/no_reproc_depl/removals_check_criticality/after_510d_no_rem.inp
and output file named /home/andrei2/Desktop/ornl/msfr/scale/no_reproc_depl/removals_check_criticality/after_510d_no_rem.out
##########################################################
***Warning: Nuclide 74180 is not contained in the specified library .
Attempting to use element 74000 failed. It is also not contained in the library
***Warning: 'Because nuclide 74180 is missing from the cross section library, its mixture 3 composition definition follows:
  b-10 3 0 3.92978e-05 973 end
  b-11 3 0 0.00014477 973 end
  c-12 3 0 0.00145833 973 end
  c-13 3 0 1.57729e-05 973 end
  al-27 3 0 0.000116061 973 end
  si-28 3 0 0.00049832 973 end
  si-29 3 0 2.53151e-05 973 end
  si-30 3 0 1.67074e-05 973 end
  p-31 3 0 4.47183e-05 973 end
  s-32 3 0 7.13609e-06 973 end
  s-33 3 0 5.63435e-08 973 end
  s-34 3 0 3.1928e-07 973 end
  s-36 3 0 7.51247e-10 973 end
  ti-46 3 0 3.06191e-05 973 end
  ti-47 3 0 2.76129e-05 973 end
  ti-48 3 0 0.000273605 973 end
  ti-49 3 0 2.00787e-05 973 end
  ti-50 3 0 1.92251e-05 973 end
  cr-50 3 0 0.000403291 973 end
  cr-52 3 0 0.00777707 973 end
  cr-53 3 0 0.000881858 973 end
  cr-54 3 0 0.000219513 973 end
  mn-55 3 0 0.000281716 973 end
  fe-54 3 0 3.98352e-05 973 end
  fe-56 3 0 0.000625328 973 end
  fe-57 3 0 1.44415e-05 973 end
  fe-58 3 0 1.9219e-06 973 end
  ni-58 3 0 0.0554827 973 end
  ni-60 3 0 0.0213718 973 end
  ni-61 3 0 0.000929018 973 end
  ni-62 3 0 0.00296212 973 end
  ni-64 3 0 0.000754364 973 end
  mo-92 3 0 6.82371e-05 973 end
  mo-94 3 0 4.26424e-05 973 end
  mo-95 3 0 7.34577e-05 973 end
  mo-96 3 0 7.70612e-05 973 end
  mo-97 3 0 4.4167e-05 973 end
  mo-98 3 0 0.000111757 973 end
  mo-100 3 0 4.46752e-05 973 end
  w-180 3 0 3.92143e-06 973 end
  w-182 3 0 0.000865982 973 end
  w-183 3 0 0.000467631 973 end
  w-184 3 0 0.00100127 973 end
  w-186 3 0 0.000929052 973 end
*** Warning - 1 issue(s) with the composition input resulting in removal of 1 nuclide(s) with a total of 3.92143e-06 atoms/barn-cm.
*** Mixture 3 density updated to 9.99883 grams/cc

*** If the default behavior is not acceptable, the above edits can be used to fix the composition input by removing or redistributing the atomic density of the missing nuclide(s).

*** This message can be suppressed by setting the environment variable MISSING_NUCLIDE_MSG_LEVEL=QUIET

*** The calculation will continue with the nuclide(s) removed, which will produce identical radiation transport and very similar activation/depletion results as using a cross section of 0.0 for each of the missing nuclide(s).

>>> Loading SCALE Standard Composition Library from /home/andrei2/SCALE/SCALE-6.2.3/data/scale.rev39.sclib
>>> Loading CE library /home/andrei2/SCALE/SCALE-6.2.3/data/ce_v7.0_endf.xml
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 24/ 2018 at 11:36:51

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.94569   2.057E-02 4.265E+00 (    4,  1)   1.000E+00 (    1,  0) 11:36:56    5.3 s     5.3 s 107.0%    F
     2    0.94743   1.841E-03 3.844E+00 (    4,  1)   2.673E-01 ( 1388,  0) 11:37:00    9.3 s     4.0 s  99.0%    F
     3    0.94841   1.034E-03 3.691E+00 (    4,  1)   8.053E-02 ( 1388,  0) 11:37:03   12.6 s     3.3 s 110.7%    F
     4    0.94890   5.075E-04 3.473E+00 (    4,  1)   2.367E-02 (    1,  0) 11:37:07   15.8 s     3.1 s  78.0%    F
     5    0.94916   2.747E-04 3.269E+00 (    4,  1)   9.688E-03 (    1,  0) 11:37:10   19.6 s     3.9 s 128.7%    F
     6    0.94928   1.276E-04 3.077E+00 (    4,  1)   4.423E-03 (   68,  0) 11:37:14   23.0 s     3.3 s  83.5%    F
     7    0.94935   7.411E-05 2.906E+00 (    4,  1)   3.514E-03 ( 1385,  0) 11:37:17   26.2 s     3.2 s 108.3%    F
     8    0.94940   5.764E-05 2.760E+00 (    4,  1)   2.689E-03 (   68,  0) 11:37:21   29.9 s     3.7 s  93.0%    F
     9    0.94944   3.652E-05 2.641E+00 (    4,  1)   2.095E-03 (   68,  0) 11:37:25   33.8 s     3.9 s  98.2%    F
    10    0.94946   2.146E-05 2.546E+00 (    4,  1)   1.580E-03 ( 1385,  0) 11:37:29   38.6 s     4.7 s 118.3%    F
    11    0.94947   1.110E-05 2.472E+00 (    4,  1)   1.180E-03 (   68,  0) 11:37:34   43.4 s     4.8 s  96.8%    T
    12    0.94947   5.755E-06 2.414E+00 (    4,  1)   8.653E-04 ( 1385,  0) 11:37:40   48.7 s     5.3 s  88.3%    T
    13    0.94948   2.830E-06 2.384E+00 (    2,  1)   6.305E-04 (   68,  0) 11:37:45   54.4 s     5.6 s 113.0%    T
 k-eff =       0.94947583     


  Time per Iteration (sec):
 Transport Sweeping:     2.031
 Inscatter Source  :     0.564
 Coarse-Mesh Accel :     2.628
 Else (Convergence):     0.174
 Total (per outer):      5.397

  Total iteration time breakdown (sec):
 Transport Sweeping:    26.408
 Inscatter Source  :     7.332
 Coarse-Mesh Accel :    34.167
 Else (Convergence):     2.257
 Total Time        :    70.164

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.49471E-01
 Equivalent core height is infinite.
The number of cross section groups is 0, but the number of flux groups is 238 in Malocs.
