SCALE Job started on Thu 26/07/2018 08:44:56
With Host name andrei2-HP-Notebook
working directory /tmp/scale.andrei2.9288
and process id 9288.
Input file named /home/andrei2/Desktop/ornl/msfr/scale/no_reproc_depl/removals_check_criticality/u233_mass_effect_gases_removal.inp
and output file named /home/andrei2/Desktop/ornl/msfr/scale/no_reproc_depl/removals_check_criticality/u233_mass_effect_gases_removal.out
##########################################################
***Warning: Nuclide 74180 is not contained in the specified library .
Attempting to use element 74000 failed. It is also not contained in the library
***Warning: 'Because nuclide 74180 is missing from the cross section library, its mixture 3 composition definition follows:
  b-10 3 0 3.92978e-05 973 end
  b-11 3 0 0.00014477 973 end
  c-12 3 0 0.00145833 973 end
  c-13 3 0 1.57729e-05 973 end
  al-27 3 0 0.000116061 973 end
  si-28 3 0 0.00049832 973 end
  si-29 3 0 2.53151e-05 973 end
  si-30 3 0 1.67074e-05 973 end
  p-31 3 0 4.47183e-05 973 end
  s-32 3 0 7.13609e-06 973 end
  s-33 3 0 5.63435e-08 973 end
  s-34 3 0 3.1928e-07 973 end
  s-36 3 0 7.51247e-10 973 end
  ti-46 3 0 3.06191e-05 973 end
  ti-47 3 0 2.76129e-05 973 end
  ti-48 3 0 0.000273605 973 end
  ti-49 3 0 2.00787e-05 973 end
  ti-50 3 0 1.92251e-05 973 end
  cr-50 3 0 0.000403291 973 end
  cr-52 3 0 0.00777707 973 end
  cr-53 3 0 0.000881858 973 end
  cr-54 3 0 0.000219513 973 end
  mn-55 3 0 0.000281716 973 end
  fe-54 3 0 3.98352e-05 973 end
  fe-56 3 0 0.000625328 973 end
  fe-57 3 0 1.44415e-05 973 end
  fe-58 3 0 1.9219e-06 973 end
  ni-58 3 0 0.0554827 973 end
  ni-60 3 0 0.0213718 973 end
  ni-61 3 0 0.000929018 973 end
  ni-62 3 0 0.00296212 973 end
  ni-64 3 0 0.000754364 973 end
  mo-92 3 0 6.82371e-05 973 end
  mo-94 3 0 4.26424e-05 973 end
  mo-95 3 0 7.34577e-05 973 end
  mo-96 3 0 7.70612e-05 973 end
  mo-97 3 0 4.4167e-05 973 end
  mo-98 3 0 0.000111757 973 end
  mo-100 3 0 4.46752e-05 973 end
  w-180 3 0 3.92143e-06 973 end
  w-182 3 0 0.000865982 973 end
  w-183 3 0 0.000467631 973 end
  w-184 3 0 0.00100127 973 end
  w-186 3 0 0.000929052 973 end
*** Warning - 1 issue(s) with the composition input resulting in removal of 1 nuclide(s) with a total of 3.92143e-06 atoms/barn-cm.
*** Mixture 3 density updated to 9.99883 grams/cc

*** If the default behavior is not acceptable, the above edits can be used to fix the composition input by removing or redistributing the atomic density of the missing nuclide(s).

*** This message can be suppressed by setting the environment variable MISSING_NUCLIDE_MSG_LEVEL=QUIET

*** The calculation will continue with the nuclide(s) removed, which will produce identical radiation transport and very similar activation/depletion results as using a cross section of 0.0 for each of the missing nuclide(s).

>>> Loading SCALE Standard Composition Library from /home/andrei2/SCALE/SCALE-6.2.3/data/scale.rev39.sclib
>>> Loading CE library /home/andrei2/SCALE/SCALE-6.2.3/data/ce_v7.0_endf.xml
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 26/ 2018 at 08:50:41

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.97218   2.653E-02 4.303E+00 (    4,  1)   1.000E+00 (    1,  0) 08:50:46    5.4 s     5.4 s 107.6%    F
     2    0.97359   1.447E-03 3.844E+00 (    4,  1)   7.584E-01 (  630,  0) 08:50:51   10.1 s     4.8 s  95.0%    F
     3    0.97451   9.453E-04 3.692E+00 (    4,  1)   6.157E-02 (  599,  0) 08:50:54   13.6 s     3.5 s 115.7%    F
     4    0.97505   5.537E-04 3.475E+00 (    4,  1)   1.868E-02 (    1,  0) 08:50:59   17.8 s     4.1 s  83.0%    F
     5    0.97534   2.942E-04 3.270E+00 (    4,  1)   8.523E-03 (    1,  0) 08:51:02   21.5 s     3.7 s 123.3%    F
     6    0.97549   1.553E-04 3.077E+00 (    4,  1)   3.827E-03 (    1,  0) 08:51:06   25.5 s     4.1 s 101.7%    F
     7    0.97557   8.402E-05 2.904E+00 (    4,  1)   1.711E-03 (    1,  0) 08:51:10   29.5 s     4.0 s  99.7%    F
     8    0.97562   5.113E-05 2.758E+00 (    4,  1)   1.053E-03 (  816,  0) 08:51:14   33.4 s     3.9 s  97.5%    F
     9    0.97565   2.711E-05 2.639E+00 (    4,  1)   7.742E-04 (  816,  0) 08:51:19   38.5 s     5.0 s 101.0%    F
    10    0.97566   1.404E-05 2.544E+00 (    4,  1)   5.543E-04 (   49,  0) 08:51:24   43.5 s     5.1 s 101.8%    F
 k-eff =       0.97566450     Collapsing solution


  Time per Iteration (sec):
 Transport Sweeping:     2.273
 Inscatter Source  :     0.556
 Coarse-Mesh Accel :     2.782
 Else (Convergence):     0.246
 Total (per outer):      5.857

  Total iteration time breakdown (sec):
 Transport Sweeping:    22.730
 Inscatter Source  :     5.557
 Coarse-Mesh Accel :    27.819
 Else (Convergence):     2.461
 Total Time        :    58.567

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.75670E-01
 Equivalent core height is infinite.
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1019  for Nuclide:       94237
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1020  for Nuclide:       94237
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1019  for Nuclide:       94244
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1020  for Nuclide:       94244
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1019  for Nuclide:       96241
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1019  for Nuclide:       96248
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1020  for Nuclide:       96248
>>> Loading CE library /home/andrei2/SCALE/SCALE-6.2.3/data/ce_v7.0_endf.xml
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 26/ 2018 at 08:52:50

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.99327   2.721E-02 4.830E-01 (    3, 49)   1.000E+00 (    1,  0) 08:52:51    0.8 s     0.8 s  80.0%    F
     2    0.99508   1.822E-03 3.608E-02 (    3, 31)   7.159E-01 ( 1087,  0) 08:52:52    1.4 s     0.6 s  60.0%    F
     3    0.99627   1.199E-03 1.921E-02 (    4, 14)   5.456E-02 (    1,  0) 08:52:52    2.0 s     0.6 s  58.0%    F
     4    0.99691   6.422E-04 1.182E-02 (    4, 14)   2.742E-02 (    1,  0) 08:52:53    2.4 s     0.4 s  43.0%    F
     5    0.99725   3.354E-04 7.094E-03 (    4, 14)   1.348E-02 (    1,  0) 08:52:53    2.8 s     0.4 s  40.0%    F
     6    0.99743   1.845E-04 4.411E-03 (    4, 16)   6.586E-03 (    1,  0) 08:52:53    3.2 s     0.4 s  37.0%    F
     7    0.99754   1.068E-04 2.929E-03 (    4, 16)   3.238E-03 (    1,  0) 08:52:54    3.5 s     0.4 s  37.0%    F
     8    0.99760   5.791E-05 2.059E-03 (    3, 18)   2.211E-03 (   49,  0) 08:52:54    3.9 s     0.4 s  39.0%    F
     9    0.99763   3.059E-05 1.736E-03 (    3, 22)   1.575E-03 (   49,  0) 08:52:55    4.3 s     0.4 s  39.0%    F
    10    0.99764   1.511E-05 1.444E-03 (    3, 22)   1.112E-03 (   49,  0) 08:52:55    4.7 s     0.4 s  39.0%    F
    11    0.99765   7.429E-06 1.174E-03 (    3, 22)   7.919E-04 (  816,  0) 08:52:55    5.1 s     0.4 s  40.0%    T
    12    0.99765   2.880E-06 9.445E-04 (    3, 22)   5.845E-04 (  595,  0) 08:52:56    5.5 s     0.4 s  41.0%    T
 k-eff =       0.99765208     Time=      0.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.346
 Inscatter Source  :     0.056
 Coarse-Mesh Accel :     0.193
 Else (Convergence):     0.033
 Total (per outer):      0.629

  Total iteration time breakdown (sec):
 Transport Sweeping:     4.155
 Inscatter Source  :     0.676
 Coarse-Mesh Accel :     2.322
 Else (Convergence):     0.390
 Total Time        :     7.543

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.97654E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 26/ 2018 at 08:53:23

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.98857   7.331E-07 5.619E-02 (    2, 42)   1.915E-01 (  230,  0) 08:53:24    0.6 s     0.6 s  62.0%    F
     2    0.98859   2.563E-05 2.903E-03 (    2, 41)   2.532E-03 (  564,  0) 08:53:24    1.2 s     0.6 s  60.0%    F
     3    0.98860   7.701E-06 7.580E-04 (    3, 45)   1.290E-03 (  884,  0) 08:53:25    1.8 s     0.6 s  60.0%    T
     4    0.98861   3.832E-06 2.205E-04 (    3, 17)   6.388E-04 (  599,  0) 08:53:26    2.4 s     0.6 s  59.0%    T
     5    0.98861   1.978E-06 1.941E-04 (    3, 17)   1.217E-04 (  694,  0) 08:53:26    3.0 s     0.6 s  61.0%    T
 k-eff =       0.98860742     Time=     15.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.244
 Inscatter Source  :     0.047
 Coarse-Mesh Accel :     0.597
 Else (Convergence):     0.062
 Total (per outer):      0.950

  Total iteration time breakdown (sec):
 Transport Sweeping:     1.220
 Inscatter Source  :     0.234
 Coarse-Mesh Accel :     2.986
 Else (Convergence):     0.310
 Total Time        :     4.750

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.88591E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 26/ 2018 at 08:53:51

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.97751   5.101E-05 2.320E-02 (    2, 41)   5.312E-01 (  230,  0) 08:53:51    0.6 s     0.6 s  59.0%    F
     2    0.97752   6.460E-06 5.109E-03 (    3, 45)   3.401E-03 (  564,  0) 08:53:52    1.2 s     0.6 s  60.0%    F
     3    0.97752   1.514E-06 2.106E-03 (    3, 43)   8.816E-04 (   51,  0) 08:53:52    1.8 s     0.6 s  60.0%    F
     4    0.97751   9.172E-08 9.227E-04 (    3, 43)   2.331E-04 (  731,  0) 08:53:53    2.4 s     0.6 s  61.0%    T
 k-eff =       0.97751498     Time=     45.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.237
 Inscatter Source  :     0.051
 Coarse-Mesh Accel :     0.553
 Else (Convergence):     0.076
 Total (per outer):      0.916

  Total iteration time breakdown (sec):
 Transport Sweeping:     0.947
 Inscatter Source  :     0.203
 Coarse-Mesh Accel :     2.212
 Else (Convergence):     0.304
 Total Time        :     3.666

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.77527E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 26/ 2018 at 08:54:17

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.97160   8.456E-05 2.465E-02 (    2, 41)   4.311E-01 (  230,  0) 08:54:18    0.6 s     0.6 s  59.0%    F
     2    0.97158   2.146E-05 5.446E-03 (    3, 45)   2.720E-03 (  696,  0) 08:54:18    1.2 s     0.6 s  60.0%    F
     3    0.97157   1.106E-05 2.266E-03 (    3, 45)   5.268E-04 (  263,  0) 08:54:19    1.8 s     0.6 s  60.0%    F
     4    0.97156   4.017E-06 1.047E-03 (    3, 43)   1.678E-04 (  857,  0) 08:54:19    2.4 s     0.6 s  60.0%    T
 k-eff =       0.97156172     Time=     75.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.237
 Inscatter Source  :     0.051
 Coarse-Mesh Accel :     0.631
 Else (Convergence):     0.077
 Total (per outer):      0.996

  Total iteration time breakdown (sec):
 Transport Sweeping:     0.949
 Inscatter Source  :     0.205
 Coarse-Mesh Accel :     2.525
 Else (Convergence):     0.307
 Total Time        :     3.986

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.71575E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 26/ 2018 at 08:54:43

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.96803   9.833E-05 2.538E-02 (    2, 41)   3.264E-01 (  331,  0) 08:54:44    0.6 s     0.6 s  59.0%    F
     2    0.96800   3.428E-05 5.635E-03 (    3, 45)   2.171E-03 (  564,  0) 08:54:44    1.2 s     0.6 s  59.0%    F
     3    0.96798   1.537E-05 2.332E-03 (    3, 45)   4.247E-04 (  263,  0) 08:54:45    1.8 s     0.6 s  59.0%    F
     4    0.96798   5.768E-06 1.097E-03 (    3, 43)   2.247E-04 (  857,  0) 08:54:46    2.4 s     0.6 s  59.0%    T
 k-eff =       0.96797794     Time=    105.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.238
 Inscatter Source  :     0.049
 Coarse-Mesh Accel :     0.413
 Else (Convergence):     0.076
 Total (per outer):      0.776

  Total iteration time breakdown (sec):
 Transport Sweeping:     0.953
 Inscatter Source  :     0.197
 Coarse-Mesh Accel :     1.651
 Else (Convergence):     0.305
 Total Time        :     3.106

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.67979E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 26/ 2018 at 08:55:10

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.96561   1.024E-04 2.507E-02 (    2, 41)   2.547E-01 (  665,  0) 08:55:11    0.7 s     0.7 s  66.0%    F
     2    0.96557   3.947E-05 5.712E-03 (    3, 45)   1.784E-03 (  564,  0) 08:55:12    1.3 s     0.7 s  66.0%    F
     3    0.96556   1.711E-05 2.358E-03 (    3, 45)   3.915E-04 (  795,  0) 08:55:12    2.0 s     0.7 s  66.0%    F
     4    0.96555   6.510E-06 1.118E-03 (    3, 43)   2.455E-04 (  857,  0) 08:55:13    2.6 s     0.6 s  61.0%    T
 k-eff =       0.96555005     Time=    135.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.258
 Inscatter Source  :     0.051
 Coarse-Mesh Accel :     0.486
 Else (Convergence):     0.084
 Total (per outer):      0.879

  Total iteration time breakdown (sec):
 Transport Sweeping:     1.034
 Inscatter Source  :     0.204
 Coarse-Mesh Accel :     1.943
 Else (Convergence):     0.335
 Total Time        :     3.516

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.65553E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 26/ 2018 at 08:55:37

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.96373   1.045E-04 2.464E-02 (    2, 41)   2.059E-01 (  665,  0) 08:55:38    0.6 s     0.6 s  61.0%    F
     2    0.96369   4.205E-05 5.734E-03 (    3, 45)   1.530E-03 (  696,  0) 08:55:39    1.2 s     0.6 s  60.0%    F
     3    0.96367   1.802E-05 2.354E-03 (    3, 45)   3.659E-04 (  795,  0) 08:55:39    1.8 s     0.6 s  60.0%    F
     4    0.96366   6.905E-06 1.118E-03 (    3, 43)   2.481E-04 (  857,  0) 08:55:40    2.4 s     0.6 s  61.0%    T
 k-eff =       0.96366370     Time=    165.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.235
 Inscatter Source  :     0.054
 Coarse-Mesh Accel :     0.469
 Else (Convergence):     0.076
 Total (per outer):      0.834

  Total iteration time breakdown (sec):
 Transport Sweeping:     0.940
 Inscatter Source  :     0.215
 Coarse-Mesh Accel :     1.877
 Else (Convergence):     0.303
 Total Time        :     3.335

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.63667E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 26/ 2018 at 08:56:05

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.96208   1.055E-04 2.396E-02 (    2, 41)   1.716E-01 (  665,  0) 08:56:06    0.6 s     0.6 s  64.0%    F
     2    0.96204   4.319E-05 5.718E-03 (    3, 45)   1.357E-03 (  564,  0) 08:56:06    1.2 s     0.6 s  60.0%    F
     3    0.96202   1.841E-05 2.336E-03 (    3, 45)   3.506E-04 (  465,  0) 08:56:07    1.9 s     0.6 s  63.0%    F
     4    0.96201   7.081E-06 1.111E-03 (    3, 43)   2.477E-04 (  263,  0) 08:56:08    2.5 s     0.7 s  66.0%    T
 k-eff =       0.96201459     Time=    195.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.247
 Inscatter Source  :     0.053
 Coarse-Mesh Accel :     0.453
 Else (Convergence):     0.076
 Total (per outer):      0.829

  Total iteration time breakdown (sec):
 Transport Sweeping:     0.988
 Inscatter Source  :     0.211
 Coarse-Mesh Accel :     1.813
 Else (Convergence):     0.306
 Total Time        :     3.318

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.61998E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 26/ 2018 at 08:56:33

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.96060   1.041E-04 2.331E-02 (    2, 41)   1.464E-01 (  665,  0) 08:56:33    0.6 s     0.6 s  59.0%    F
     2    0.96055   4.320E-05 5.673E-03 (    3, 45)   1.210E-03 (  696,  0) 08:56:34    1.2 s     0.6 s  60.0%    F
     3    0.96054   1.844E-05 2.307E-03 (    3, 45)   3.360E-04 (  465,  0) 08:56:35    1.8 s     0.6 s  59.0%    F
     4    0.96053   7.138E-06 1.096E-03 (    3, 43)   2.428E-04 (  857,  0) 08:56:35    2.4 s     0.6 s  61.0%    T
 k-eff =       0.96052913     Time=    225.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.238
 Inscatter Source  :     0.050
 Coarse-Mesh Accel :     0.563
 Else (Convergence):     0.076
 Total (per outer):      0.927

  Total iteration time breakdown (sec):
 Transport Sweeping:     0.951
 Inscatter Source  :     0.200
 Coarse-Mesh Accel :     2.251
 Else (Convergence):     0.306
 Total Time        :     3.708

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.60538E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 26/ 2018 at 08:57:01

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.95919   1.033E-04 2.268E-02 (    2, 41)   1.273E-01 (  665,  0) 08:57:01    0.6 s     0.6 s  64.0%    F
     2    0.95914   4.322E-05 5.631E-03 (    3, 45)   1.101E-03 (  564,  0) 08:57:02    1.3 s     0.6 s  62.0%    F
     3    0.95913   1.849E-05 2.279E-03 (    3, 45)   3.244E-04 (  795,  0) 08:57:03    1.9 s     0.6 s  60.0%    F
     4    0.95912   7.190E-06 1.082E-03 (    3, 43)   2.382E-04 (  857,  0) 08:57:03    2.5 s     0.6 s  61.0%    T
 k-eff =       0.95911895     Time=    255.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.242
 Inscatter Source  :     0.052
 Coarse-Mesh Accel :     0.588
 Else (Convergence):     0.076
 Total (per outer):      0.958

  Total iteration time breakdown (sec):
 Transport Sweeping:     0.967
 Inscatter Source  :     0.208
 Coarse-Mesh Accel :     2.352
 Else (Convergence):     0.305
 Total Time        :     3.832

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.59109E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 26/ 2018 at 08:57:29

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.95782   1.019E-04 2.202E-02 (    2, 41)   1.123E-01 (  731,  0) 08:57:29    0.7 s     0.7 s  68.0%    F
     2    0.95778   4.289E-05 5.572E-03 (    3, 45)   1.008E-03 (  696,  0) 08:57:30    1.4 s     0.7 s  67.0%    F
     3    0.95776   1.840E-05 2.246E-03 (    3, 45)   3.160E-04 (  465,  0) 08:57:31    2.0 s     0.7 s  67.0%    F
     4    0.95776   7.190E-06 1.066E-03 (    3, 43)   2.344E-04 (  263,  0) 08:57:31    2.7 s     0.7 s  66.0%    T
 k-eff =       0.95775798     Time=    285.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.268
 Inscatter Source  :     0.057
 Coarse-Mesh Accel :     0.603
 Else (Convergence):     0.085
 Total (per outer):      1.013

  Total iteration time breakdown (sec):
 Transport Sweeping:     1.071
 Inscatter Source  :     0.228
 Coarse-Mesh Accel :     2.411
 Else (Convergence):     0.341
 Total Time        :     4.051

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.57742E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 26/ 2018 at 08:58:04

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.95650   1.008E-04 2.091E-02 (    3, 49)   1.004E-01 (  599,  0) 08:58:05    1.2 s     1.2 s 125.0%    F
     2    0.95646   4.260E-05 5.491E-03 (    3, 45)   9.473E-04 (  599,  0) 08:58:06    2.4 s     1.1 s 114.0%    F
     3    0.95644   1.831E-05 2.202E-03 (    3, 45)   3.017E-04 (  465,  0) 08:58:07    3.5 s     1.1 s 115.0%    F
 k-eff =       0.95643780     Time=    315.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.510
 Inscatter Source  :     0.100
 Coarse-Mesh Accel :     1.116
 Else (Convergence):     0.231
 Total (per outer):      1.957

  Total iteration time breakdown (sec):
 Transport Sweeping:     1.531
 Inscatter Source  :     0.299
 Coarse-Mesh Accel :     3.348
 Else (Convergence):     0.693
 Total Time        :     5.871

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.56439E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 26/ 2018 at 08:58:48

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.95520   1.010E-04 2.088E-02 (    3, 49)   9.068E-02 (  731,  0) 08:58:49    1.2 s     1.2 s 116.0%    F
     2    0.95515   4.355E-05 5.626E-03 (    3, 45)   1.011E-03 (  731,  0) 08:58:51    2.5 s     1.3 s  66.0%    F
     3    0.95514   1.866E-05 2.278E-03 (    3, 45)   3.252E-04 (  795,  0) 08:58:52    3.9 s     1.4 s 139.0%    F
     4    0.95513   7.297E-06 1.091E-03 (    3, 43)   2.476E-04 (  263,  0) 08:58:54    5.3 s     1.4 s  71.0%    T
 k-eff =       0.95512887     Time=    345.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.672
 Inscatter Source  :     0.144
 Coarse-Mesh Accel :     1.077
 Else (Convergence):     0.145
 Total (per outer):      2.038

  Total iteration time breakdown (sec):
 Transport Sweeping:     2.690
 Inscatter Source  :     0.577
 Coarse-Mesh Accel :     4.308
 Else (Convergence):     0.579
 Total Time        :     8.154

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.55146E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 26/ 2018 at 08:59:55

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.95391   9.832E-05 2.075E-02 (    3, 49)   8.252E-02 (  731,  0) 08:59:56    1.1 s     1.1 s 106.0%    F
     2    0.95387   4.190E-05 5.349E-03 (    3, 45)   9.214E-04 (  599,  0) 08:59:57    2.2 s     1.2 s 116.0%    F
     3    0.95385   1.810E-05 2.132E-03 (    3, 45)   2.887E-04 (  795,  0) 08:59:59    3.4 s     1.2 s  59.0%    F
 k-eff =       0.95385440     Time=    375.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.451
 Inscatter Source  :     0.091
 Coarse-Mesh Accel :     1.277
 Else (Convergence):     0.281
 Total (per outer):      2.100

  Total iteration time breakdown (sec):
 Transport Sweeping:     1.354
 Inscatter Source  :     0.272
 Coarse-Mesh Accel :     3.832
 Else (Convergence):     0.843
 Total Time        :     6.301

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.53834E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 26/ 2018 at 09:00:35

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.95263   9.905E-05 2.067E-02 (    3, 49)   7.569E-02 (  731,  0) 09:00:36    1.0 s     1.0 s 104.0%    F
     2    0.95259   4.283E-05 5.438E-03 (    3, 45)   9.696E-04 (  599,  0) 09:00:37    2.0 s     1.0 s  98.0%    F
     3    0.95257   1.842E-05 2.186E-03 (    3, 45)   3.066E-04 (  795,  0) 09:00:38    3.0 s     1.0 s  95.0%    F
 k-eff =       0.95257127     Time=    405.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.421
 Inscatter Source  :     0.090
 Coarse-Mesh Accel :     0.981
 Else (Convergence):     0.166
 Total (per outer):      1.658

  Total iteration time breakdown (sec):
 Transport Sweeping:     1.264
 Inscatter Source  :     0.271
 Coarse-Mesh Accel :     2.942
 Else (Convergence):     0.498
 Total Time        :     4.975

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.52583E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 26/ 2018 at 09:01:12

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.95136   9.747E-05 2.271E-02 (    3, 48)   6.982E-02 (  731,  0) 09:01:12    0.9 s     0.9 s  90.0%    F
     2    0.95132   4.228E-05 5.356E-03 (    3, 45)   9.641E-04 (  599,  0) 09:01:13    1.7 s     0.8 s  83.0%    F
     3    0.95130   1.823E-05 2.155E-03 (    3, 45)   3.070E-04 (  795,  0) 09:01:14    2.5 s     0.8 s  77.0%    F
 k-eff =       0.95130425     Time=    435.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.361
 Inscatter Source  :     0.074
 Coarse-Mesh Accel :     0.651
 Else (Convergence):     0.138
 Total (per outer):      1.223

  Total iteration time breakdown (sec):
 Transport Sweeping:     1.083
 Inscatter Source  :     0.222
 Coarse-Mesh Accel :     1.952
 Else (Convergence):     0.413
 Total Time        :     3.670

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.51317E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 26/ 2018 at 09:01:46

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.95013   9.588E-05 2.087E-02 (    3, 49)   6.473E-02 (  599,  0) 09:01:47    0.8 s     0.8 s  79.0%    F
     2    0.95009   4.186E-05 5.271E-03 (    3, 45)   9.419E-04 (  599,  0) 09:01:48    1.6 s     0.8 s  79.0%    F
     3    0.95007   1.811E-05 2.109E-03 (    3, 45)   3.005E-04 (  795,  0) 09:01:49    2.4 s     0.8 s  78.0%    F
 k-eff =       0.95007396     Time=    465.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.304
 Inscatter Source  :     0.066
 Coarse-Mesh Accel :     0.916
 Else (Convergence):     0.129
 Total (per outer):      1.415

  Total iteration time breakdown (sec):
 Transport Sweeping:     0.912
 Inscatter Source  :     0.198
 Coarse-Mesh Accel :     2.748
 Else (Convergence):     0.387
 Total Time        :     4.245

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.50075E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 26/ 2018 at 09:02:22

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.94892   9.476E-05 2.032E-02 (    3, 49)   6.030E-02 (  731,  0) 09:02:23    0.7 s     0.7 s  67.0%    F
     2    0.94888   4.151E-05 5.164E-03 (    3, 45)   9.154E-04 (  731,  0) 09:02:24    1.4 s     0.7 s  71.0%    F
     3    0.94886   1.802E-05 2.058E-03 (    3, 45)   2.909E-04 (  465,  0) 09:02:24    2.1 s     0.7 s  73.0%    T
 k-eff =       0.94886349     Time=    495.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.273
 Inscatter Source  :     0.059
 Coarse-Mesh Accel :     0.543
 Else (Convergence):     0.106
 Total (per outer):      0.980

  Total iteration time breakdown (sec):
 Transport Sweeping:     0.819
 Inscatter Source  :     0.176
 Coarse-Mesh Accel :     1.628
 Else (Convergence):     0.317
 Total Time        :     2.940

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.48853E-01
 Equivalent core height is infinite.
