SCALE Job started on Wed 01/08/2018 12:41:16
With Host name andrei2-HP-Notebook
working directory /tmp/scale.andrei2.27360
and process id 27360.
Input file named /home/andrei2/Desktop/ornl/mosart/scale/mosart_quarter_higher_k.inp
and output file named /home/andrei2/Desktop/ornl/mosart/scale/mosart_quarter_higher_k.out
##########################################################
>>> Loading SCALE Standard Composition Library from /home/andrei2/SCALE/SCALE-6.2.3/data/scale.rev39.sclib
>>> Loading CE library /home/andrei2/SCALE/SCALE-6.2.3/data/ce_v7.0_endf.xml
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 01/ 2018 at 12:41:47

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.01612   9.533E-03 6.907E-01 (    4,184)   1.000E+00 (    2,  0) 12:41:48    1.1 s     1.1 s 107.0%    F
     2    1.01653   4.041E-04 1.037E-01 (    3,  8)   2.913E+00 (  268,  0) 12:41:49    2.0 s     0.9 s  91.0%    F
     3    1.01632   2.082E-04 2.828E-02 (    4, 56)   1.056E-01 (    3,  0) 12:41:50    3.0 s     1.0 s  98.0%    F
     4    1.01620   1.144E-04 1.266E-02 (    4, 56)   2.551E-02 (    3,  0) 12:41:51    4.1 s     1.1 s 113.0%    F
     5    1.01623   2.748E-05 5.520E-03 (    4, 56)   8.293E-03 (    3,  0) 12:41:53    5.4 s     1.3 s  64.0%    F
     6    1.01628   4.303E-05 2.382E-03 (    4, 56)   3.008E-03 (    3,  0) 12:41:54    6.7 s     1.3 s 135.0%    F
     7    1.01630   2.230E-05 1.023E-03 (    4, 56)   1.246E-03 (  269,  0) 12:41:55    8.2 s     1.4 s 144.0%    F
     8    1.01631   9.806E-06 4.411E-04 (    4, 56)   5.655E-04 (  269,  0) 12:41:57    9.7 s     1.6 s  78.5%    F
     9    1.01631   4.523E-06 1.917E-04 (    4, 56)   2.642E-04 (  269,  0) 12:41:58   11.3 s     1.6 s 158.0%    F
 k-eff =       1.01631326     


  Time per Iteration (sec):
 Transport Sweeping:     0.446
 Inscatter Source  :     0.088
 Coarse-Mesh Accel :     0.872
 Else (Convergence):     0.050
 Total (per outer):      1.456

  Total iteration time breakdown (sec):
 Transport Sweeping:     4.010
 Inscatter Source  :     0.791
 Coarse-Mesh Accel :     7.851
 Else (Convergence):     0.453
 Total Time        :    13.105

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.01631E+00
 Equivalent core height is infinite.
The number of cross section groups is 0, but the number of flux groups is 238 in Malocs.
