SCALE Job started on Thu 21/06/2018 11:37:23
With Host name andrei2-HP-Notebook
working directory /tmp/scale.andrei2.27599
and process id 27599.
Input file named /home/andrei2/Desktop/ornl/mosart/scale/mosart_quarter.inp
and output file named /home/andrei2/Desktop/ornl/mosart/scale/mosart_quarter.out
##########################################################
>>> Loading SCALE Standard Composition Library from /home/andrei2/SCALE/SCALE-6.2.3/data/scale.rev39.sclib
>>> Loading CE library /home/andrei2/SCALE/SCALE-6.2.3/data/ce_v7.0_endf.xml
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
 ===================================================================================================================================
   Outer iteration sweep begins 06/ 21/ 2018 at 11:38:05

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.01701   1.064E-02 3.578E-01 (    4,184)   1.000E+00 (    2,  0) 11:38:50   44.2 s    44.2 s  98.1%    F
     2    1.01060   6.343E-03 6.163E-02 (    3,  1)   1.114E+00 ( 2362,  0) 11:39:34   88.5 s    44.4 s 100.9%    F
     3    1.00905   1.534E-03 9.716E-03 (    3,  1)   9.818E-02 (    2,  0) 11:40:26  140.1 s    51.6 s  99.2%    F
     4    1.00778   1.257E-03 3.264E-03 (    4, 74)   7.469E-03 (    3,  0) 11:41:18  191.3 s    51.2 s  98.4%    F
     5    1.00665   1.127E-03 2.145E-03 (    4,146)   2.867E-03 (  969,  0) 11:41:56  228.9 s    37.6 s  99.0%    F
     6    1.00594   7.076E-04 1.707E-03 (    2,225)   1.818E-03 (  866,  0) 11:42:49  274.7 s    45.8 s  86.4%    F
     7    1.00548   4.553E-04 1.374E-03 (    2,225)   1.467E-03 ( 2365,  0) 11:43:28  313.4 s    38.7 s  99.2%    F
     8    1.00514   3.376E-04 1.045E-03 (    2,225)   1.079E-03 ( 2355,  0) 11:44:04  348.6 s    35.3 s  97.9%    F
     9    1.00489   2.440E-04 7.687E-04 (    2,225)   8.004E-04 ( 2355,  0) 11:44:39  384.2 s    35.6 s 101.7%    F
    10    1.00473   1.644E-04 5.612E-04 (    2,225)   5.806E-04 ( 2365,  0) 11:45:12  417.1 s    32.8 s  99.5%    F
 k-eff =       1.00472773     


  Time per Iteration (sec):
 Transport Sweeping:    24.011
 Inscatter Source  :     1.534
 Coarse-Mesh Accel :    19.216
 Else (Convergence):     0.107
 Total (per outer):     44.867

  Total iteration time breakdown (sec):
 Transport Sweeping:   240.106
 Inscatter Source  :    15.336
 Coarse-Mesh Accel :   192.161
 Else (Convergence):     1.071
 Total Time        :   448.674

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.00437E+00
 Equivalent core height is infinite.
The number of cross section groups is 0, but the number of flux groups is 238 in Malocs.
