SCALE Job started on Wed 01/08/2018 13:15:53
With Host name andrei2-HP-Notebook
working directory /tmp/scale.andrei2.1088
and process id 1088.
Input file named /home/andrei2/Desktop/ornl/mosart/scale/mosart_quarter_higher_k.inp
and output file named /home/andrei2/Desktop/ornl/mosart/scale/mosart_quarter_higher_k.out
##########################################################
>>> Loading SCALE Standard Composition Library from /home/andrei2/SCALE/SCALE-6.2.3/data/scale.rev39.sclib
>>> Loading CE library /home/andrei2/SCALE/SCALE-6.2.3/data/ce_v7.0_endf.xml
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 01/ 2018 at 13:16:13

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.01164   9.618E-03 6.889E-01 (    4,184)   1.000E+00 (    2,  0) 13:16:14    1.4 s     1.4 s 137.0%    F
     2    1.01216   5.072E-04 1.031E-01 (    3,  8)   2.901E+00 (  268,  0) 13:16:15    2.4 s     1.0 s  99.0%    F
     3    1.01192   2.373E-04 2.837E-02 (    4, 56)   1.056E-01 (    3,  0) 13:16:17    3.9 s     1.6 s  77.5%    F
     4    1.01182   1.002E-04 1.265E-02 (    4, 56)   2.554E-02 (    3,  0) 13:16:19    5.6 s     1.6 s  82.5%    F
     5    1.01184   2.861E-05 5.524E-03 (    4, 56)   8.265E-03 (    3,  0) 13:16:21    7.6 s     2.1 s 103.5%    F
     6    1.01189   4.301E-05 2.384E-03 (    4, 56)   3.002E-03 (    3,  0) 13:16:23    9.4 s     1.8 s  88.5%    F
     7    1.01191   2.227E-05 1.025E-03 (    4, 56)   1.249E-03 (  269,  0) 13:16:24   11.3 s     1.9 s 194.0%    F
     8    1.01192   9.783E-06 4.418E-04 (    4, 56)   5.664E-04 (  269,  0) 13:16:26   13.3 s     1.9 s  97.0%    F
     9    1.01193   4.512E-06 1.921E-04 (    4, 56)   2.647E-04 (  269,  0) 13:16:28   15.2 s     1.9 s  97.0%    F
 k-eff =       1.01192516     


  Time per Iteration (sec):
 Transport Sweeping:     0.615
 Inscatter Source  :     0.142
 Coarse-Mesh Accel :     1.194
 Else (Convergence):     0.063
 Total (per outer):      2.014

  Total iteration time breakdown (sec):
 Transport Sweeping:     5.535
 Inscatter Source  :     1.277
 Coarse-Mesh Accel :    10.746
 Else (Convergence):     0.565
 Total Time        :    18.123

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.01193E+00
 Equivalent core height is infinite.
The number of cross section groups is 0, but the number of flux groups is 238 in Malocs.
