SCALE Job started on Fri 10/08/2018 11:18:46
With Host name andrei2-HP-Notebook
working directory /tmp/scale.andrei2.19349
and process id 19349.
Input file named /home/andrei2/Desktop/ornl/msfr/scale/no_reproc_depl/510efpd/quarter_cell2.inp
and output file named /home/andrei2/Desktop/ornl/msfr/scale/no_reproc_depl/510efpd/quarter_cell2.out
##########################################################
***Warning: Nuclide 74180 is not contained in the specified library .
Attempting to use element 74000 failed. It is also not contained in the library
***Warning: 'Because nuclide 74180 is missing from the cross section library, its mixture 3 composition definition follows:
  b-10 3 0 3.92978e-05 973 end
  b-11 3 0 0.00014477 973 end
  c-12 3 0 0.00145833 973 end
  c-13 3 0 1.57729e-05 973 end
  al-27 3 0 0.000116061 973 end
  si-28 3 0 0.00049832 973 end
  si-29 3 0 2.53151e-05 973 end
  si-30 3 0 1.67074e-05 973 end
  p-31 3 0 4.47183e-05 973 end
  s-32 3 0 7.13609e-06 973 end
  s-33 3 0 5.63435e-08 973 end
  s-34 3 0 3.1928e-07 973 end
  s-36 3 0 7.51247e-10 973 end
  ti-46 3 0 3.06191e-05 973 end
  ti-47 3 0 2.76129e-05 973 end
  ti-48 3 0 0.000273605 973 end
  ti-49 3 0 2.00787e-05 973 end
  ti-50 3 0 1.92251e-05 973 end
  cr-50 3 0 0.000403291 973 end
  cr-52 3 0 0.00777707 973 end
  cr-53 3 0 0.000881858 973 end
  cr-54 3 0 0.000219513 973 end
  mn-55 3 0 0.000281716 973 end
  fe-54 3 0 3.98352e-05 973 end
  fe-56 3 0 0.000625328 973 end
  fe-57 3 0 1.44415e-05 973 end
  fe-58 3 0 1.9219e-06 973 end
  ni-58 3 0 0.0554827 973 end
  ni-60 3 0 0.0213718 973 end
  ni-61 3 0 0.000929018 973 end
  ni-62 3 0 0.00296212 973 end
  ni-64 3 0 0.000754364 973 end
  mo-92 3 0 6.82371e-05 973 end
  mo-94 3 0 4.26424e-05 973 end
  mo-95 3 0 7.34577e-05 973 end
  mo-96 3 0 7.70612e-05 973 end
  mo-97 3 0 4.4167e-05 973 end
  mo-98 3 0 0.000111757 973 end
  mo-100 3 0 4.46752e-05 973 end
  w-180 3 0 3.92143e-06 973 end
  w-182 3 0 0.000865982 973 end
  w-183 3 0 0.000467631 973 end
  w-184 3 0 0.00100127 973 end
  w-186 3 0 0.000929052 973 end
*** Warning - 1 issue(s) with the composition input resulting in removal of 1 nuclide(s) with a total of 3.92143e-06 atoms/barn-cm.
*** Mixture 3 density updated to 9.99883 grams/cc

*** If the default behavior is not acceptable, the above edits can be used to fix the composition input by removing or redistributing the atomic density of the missing nuclide(s).

*** This message can be suppressed by setting the environment variable MISSING_NUCLIDE_MSG_LEVEL=QUIET

*** The calculation will continue with the nuclide(s) removed, which will produce identical radiation transport and very similar activation/depletion results as using a cross section of 0.0 for each of the missing nuclide(s).

>>> Loading SCALE Standard Composition Library from /home/andrei2/SCALE/SCALE-6.2.3/data/scale.rev39.sclib
>>> Loading CE library /home/andrei2/SCALE/SCALE-6.2.3/data/ce_v7.0_endf.xml
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 10/ 2018 at 11:22:15

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.99320   1.440E-02 4.329E+00 (    4,  1)   1.000E+00 (    1,  0) 11:22:25    9.7 s     9.7 s  97.0%    F
     2    0.99400   8.070E-04 3.846E+00 (    4,  1)   5.535E-01 ( 2395,  0) 11:22:31   16.1 s     6.4 s 106.2%    F
     3    0.99464   6.506E-04 3.691E+00 (    4,  1)   5.283E-02 ( 1575,  0) 11:22:36   20.7 s     4.6 s  92.6%    F
     4    0.99500   3.599E-04 3.472E+00 (    4,  1)   2.012E-02 (    1,  0) 11:22:44   29.1 s     8.4 s 104.9%    F
     5    0.99519   1.894E-04 3.268E+00 (    4,  1)   8.177E-03 (    1,  0) 11:22:53   37.5 s     8.5 s  94.0%    F
     6    0.99530   1.073E-04 3.077E+00 (    4,  1)   3.360E-03 (    1,  0) 11:23:03   48.0 s    10.4 s 104.3%    F
     7    0.99536   5.985E-05 2.905E+00 (    4,  1)   1.503E-03 (    1,  0) 11:23:17   61.8 s    13.8 s  98.6%    F
     8    0.99539   3.008E-05 2.760E+00 (    4,  1)   7.042E-04 (    1,  0) 11:23:28   72.6 s    10.8 s  98.1%    F
     9    0.99540   1.666E-05 2.641E+00 (    4,  1)   3.885E-04 (   73,  0) 11:23:38   82.4 s     9.8 s  98.3%    T
 k-eff =       0.99540408     Collapsing solution


  Time per Iteration (sec):
 Transport Sweeping:     3.289
 Inscatter Source  :     0.783
 Coarse-Mesh Accel :     7.344
 Else (Convergence):     0.355
 Total (per outer):     11.771

  Total iteration time breakdown (sec):
 Transport Sweeping:    29.603
 Inscatter Source  :     7.046
 Coarse-Mesh Accel :    66.095
 Else (Convergence):     3.192
 Total Time        :   105.936

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.95393E-01
 Equivalent core height is infinite.
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1019  for Nuclide:       94237
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1020  for Nuclide:       94237
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1019  for Nuclide:       94244
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1020  for Nuclide:       94244
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1019  for Nuclide:       96241
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1019  for Nuclide:       96248
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1020  for Nuclide:       96248
>>> Loading CE library /home/andrei2/SCALE/SCALE-6.2.3/data/ce_v7.0_endf.xml
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 10/ 2018 at 11:26:33

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.01368   1.565E-02 3.146E-01 (    4, 16)   1.000E+00 (    1,  0) 11:26:35    1.6 s     1.6 s  78.0%    F
     2    1.01507   1.372E-03 4.208E-02 (    3, 22)   5.385E-01 ( 1575,  0) 11:26:36    2.8 s     1.2 s 121.0%    F
     3    1.01582   7.390E-04 1.297E-02 (    4, 18)   6.335E-02 (    1,  0) 11:26:37    3.9 s     1.1 s 112.0%    F
     4    1.01617   3.433E-04 7.177E-03 (    4, 14)   2.623E-02 (    1,  0) 11:26:38    4.8 s     0.9 s  87.0%    F
     5    1.01634   1.701E-04 4.150E-03 (    4, 14)   1.105E-02 (    1,  0) 11:26:39    5.6 s     0.9 s  87.0%    F
     6    1.01645   1.019E-04 2.550E-03 (    4, 15)   4.714E-03 (    1,  0) 11:26:40    6.7 s     1.0 s 104.0%    F
     7    1.01650   5.354E-05 1.624E-03 (    4, 15)   2.299E-03 (    1,  0) 11:26:41    7.7 s     1.0 s 102.0%    F
     8    1.01653   3.073E-05 1.049E-03 (    4, 16)   1.223E-03 ( 1800,  0) 11:26:42    8.7 s     1.0 s 101.0%    T
     9    1.01655   1.879E-05 6.914E-04 (    4, 16)   8.037E-04 ( 1800,  0) 11:26:43    9.7 s     1.0 s 101.0%    T
    10    1.01656   1.179E-05 4.833E-04 (    3, 22)   5.380E-04 (   73,  0) 11:26:44   10.8 s     1.1 s 108.0%    T
 k-eff =       1.01656191     Time=      0.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.707
 Inscatter Source  :     0.110
 Coarse-Mesh Accel :     0.505
 Else (Convergence):     0.067
 Total (per outer):      1.388

  Total iteration time breakdown (sec):
 Transport Sweeping:     7.068
 Inscatter Source  :     1.097
 Coarse-Mesh Accel :     5.049
 Else (Convergence):     0.670
 Total Time        :    13.884

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.01658E+00
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 10/ 2018 at 11:27:13

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.00753   1.899E-05 4.809E-02 (    2, 42)   1.981E-01 ( 1910,  0) 11:27:15    2.0 s     2.0 s  98.0%    F
     2    1.00758   4.245E-05 2.609E-03 (    4,  1)   2.109E-03 (   78,  0) 11:27:17    3.9 s     1.9 s  96.5%    F
     3    1.00759   8.674E-06 7.230E-04 (    3, 45)   1.292E-03 (   78,  0) 11:27:19    5.8 s     1.9 s  96.5%    T
     4    1.00759   3.796E-06 2.321E-04 (    3, 44)   4.178E-04 ( 1769,  0) 11:27:20    7.5 s     1.7 s 172.0%    T
     5    1.00759   1.693E-06 6.696E-05 (    4, 16)   6.852E-05 ( 1949,  0) 11:27:22    9.4 s     1.8 s  90.5%    T
 k-eff =       1.00759174     Time=     15.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.614
 Inscatter Source  :     0.126
 Coarse-Mesh Accel :     1.504
 Else (Convergence):     0.138
 Total (per outer):      2.381

  Total iteration time breakdown (sec):
 Transport Sweeping:     3.070
 Inscatter Source  :     0.629
 Coarse-Mesh Accel :     7.520
 Else (Convergence):     0.688
 Total Time        :    11.907

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.00762E+00
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 10/ 2018 at 11:27:53

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.99641   9.862E-05 2.017E-02 (    2, 41)   5.400E-01 (  737,  0) 11:27:55    1.8 s     1.8 s  88.5%    F
     2    0.99644   3.042E-05 4.026E-03 (    3, 45)   2.598E-03 (   78,  0) 11:27:56    3.6 s     1.8 s 182.0%    F
     3    0.99644   2.940E-06 1.666E-03 (    3, 44)   1.056E-03 (   80,  0) 11:27:59    5.8 s     2.2 s  72.0%    F
     4    0.99644   2.051E-06 6.966E-04 (    3, 43)   1.178E-04 (   78,  0) 11:28:01    7.9 s     2.2 s 108.0%    T
     5    0.99645   1.322E-06 3.111E-04 (    3, 43)   9.423E-05 ( 1281,  0) 11:28:03    9.9 s     1.9 s  97.0%    T
 k-eff =       0.99644539     Time=     45.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.663
 Inscatter Source  :     0.130
 Coarse-Mesh Accel :     1.555
 Else (Convergence):     0.147
 Total (per outer):      2.496

  Total iteration time breakdown (sec):
 Transport Sweeping:     3.316
 Inscatter Source  :     0.651
 Coarse-Mesh Accel :     7.777
 Else (Convergence):     0.734
 Total Time        :    12.478

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.96466E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 10/ 2018 at 11:28:31

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.99033   1.670E-04 2.151E-02 (    2, 41)   4.358E-01 ( 1955,  0) 11:28:33    1.7 s     1.7 s  86.0%    F
     2    0.99033   1.856E-06 4.062E-03 (    3, 45)   2.078E-03 ( 1328,  0) 11:28:35    3.6 s     1.9 s  95.0%    F
     3    0.99032   5.187E-06 1.660E-03 (    3, 44)   5.375E-04 (   80,  0) 11:28:37    5.5 s     1.9 s  94.0%    T
     4    0.99032   9.698E-07 7.271E-04 (    3, 43)   1.894E-04 ( 1949,  0) 11:28:39    7.6 s     2.1 s 102.5%    T
 k-eff =       0.99032368     Time=     75.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.604
 Inscatter Source  :     0.129
 Coarse-Mesh Accel :     1.528
 Else (Convergence):     0.171
 Total (per outer):      2.432

  Total iteration time breakdown (sec):
 Transport Sweeping:     2.418
 Inscatter Source  :     0.514
 Coarse-Mesh Accel :     6.112
 Else (Convergence):     0.685
 Total Time        :     9.729

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.90323E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 10/ 2018 at 11:29:10

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.98655   1.328E-04 2.153E-02 (    2, 41)   3.290E-01 ( 1955,  0) 11:29:11    1.8 s     1.8 s 175.0%    F
     2    0.98654   1.615E-05 4.168E-03 (    3, 45)   1.783E-03 (  338,  0) 11:29:13    3.4 s     1.6 s  80.5%    F
     3    0.98653   9.175E-06 1.698E-03 (    3, 44)   3.929E-04 (   80,  0) 11:29:15    5.0 s     1.7 s  83.0%    T
     4    0.98653   2.538E-06 7.582E-04 (    3, 43)   2.310E-04 ( 1949,  0) 11:29:17    6.9 s     1.9 s  96.5%    T
 k-eff =       0.98652562     Time=    105.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.592
 Inscatter Source  :     0.123
 Coarse-Mesh Accel :     1.428
 Else (Convergence):     0.186
 Total (per outer):      2.329

  Total iteration time breakdown (sec):
 Transport Sweeping:     2.370
 Inscatter Source  :     0.491
 Coarse-Mesh Accel :     5.711
 Else (Convergence):     0.746
 Total Time        :     9.318

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.86535E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 10/ 2018 at 11:29:47

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.98390   1.060E-04 2.114E-02 (    2, 41)   2.562E-01 (  389,  0) 11:29:49    1.7 s     1.7 s  87.0%    F
     2    0.98388   2.202E-05 4.230E-03 (    3, 45)   1.539E-03 ( 1905,  0) 11:29:51    3.5 s     1.8 s  87.5%    F
     3    0.98387   1.038E-05 1.711E-03 (    3, 44)   3.474E-04 ( 1949,  0) 11:29:53    5.5 s     2.0 s  98.5%    T
     4    0.98387   2.975E-06 7.692E-04 (    3, 43)   2.464E-04 (   80,  0) 11:29:55    7.4 s     1.9 s  95.5%    T
 k-eff =       0.98386517     Time=    135.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.602
 Inscatter Source  :     0.128
 Coarse-Mesh Accel :     1.503
 Else (Convergence):     0.168
 Total (per outer):      2.401

  Total iteration time breakdown (sec):
 Transport Sweeping:     2.407
 Inscatter Source  :     0.512
 Coarse-Mesh Accel :     6.011
 Else (Convergence):     0.673
 Total Time        :     9.603

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.83892E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 10/ 2018 at 11:30:27

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.98177   1.001E-04 2.074E-02 (    2, 41)   2.069E-01 ( 1955,  0) 11:30:29    2.3 s     2.3 s 117.5%    F
     2    0.98175   2.510E-05 4.253E-03 (    3, 45)   1.369E-03 (  338,  0) 11:30:32    4.7 s     2.4 s  78.7%    F
     3    0.98174   1.099E-05 1.707E-03 (    3, 44)   3.197E-04 ( 1949,  0) 11:30:34    6.8 s     2.0 s 102.0%    T
     4    0.98174   3.196E-06 7.695E-04 (    3, 43)   2.472E-04 ( 1949,  0) 11:30:36    8.6 s     1.9 s  94.5%    T
 k-eff =       0.98173558     Time=    165.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.691
 Inscatter Source  :     0.141
 Coarse-Mesh Accel :     1.990
 Else (Convergence):     0.247
 Total (per outer):      3.068

  Total iteration time breakdown (sec):
 Transport Sweeping:     2.764
 Inscatter Source  :     0.563
 Coarse-Mesh Accel :     7.958
 Else (Convergence):     0.987
 Total Time        :    12.272

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.81743E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 10/ 2018 at 11:31:08

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.97989   9.881E-05 2.031E-02 (    2, 41)   1.723E-01 ( 1955,  0) 11:31:10    1.8 s     1.8 s  91.5%    F
     2    0.97986   2.651E-05 4.258E-03 (    3, 45)   1.249E-03 (  338,  0) 11:31:12    3.7 s     1.8 s  92.0%    F
     3    0.97985   1.131E-05 1.698E-03 (    3, 44)   3.035E-04 (   80,  0) 11:31:13    5.6 s     1.9 s 195.0%    T
     4    0.97984   3.332E-06 7.662E-04 (    3, 43)   2.450E-04 ( 1949,  0) 11:31:15    7.5 s     1.9 s  95.5%    T
 k-eff =       0.97984495     Time=    195.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.592
 Inscatter Source  :     0.130
 Coarse-Mesh Accel :     1.645
 Else (Convergence):     0.171
 Total (per outer):      2.539

  Total iteration time breakdown (sec):
 Transport Sweeping:     2.367
 Inscatter Source  :     0.521
 Coarse-Mesh Accel :     6.581
 Else (Convergence):     0.685
 Total Time        :    10.154

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.79832E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 10/ 2018 at 11:31:48

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.97816   9.693E-05 1.986E-02 (    2, 41)   1.469E-01 (  389,  0) 11:31:49    1.8 s     1.8 s 178.0%    F
     2    0.97813   2.727E-05 4.245E-03 (    3, 45)   1.142E-03 ( 1905,  0) 11:31:51    3.5 s     1.7 s  86.5%    F
     3    0.97812   1.146E-05 1.683E-03 (    3, 44)   2.908E-04 (   80,  0) 11:31:53    5.2 s     1.7 s  85.0%    T
     4    0.97812   3.433E-06 7.591E-04 (    3, 44)   2.400E-04 (   80,  0) 11:31:55    6.9 s     1.7 s  86.5%    T
 k-eff =       0.97811590     Time=    225.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.577
 Inscatter Source  :     0.129
 Coarse-Mesh Accel :     1.449
 Else (Convergence):     0.178
 Total (per outer):      2.333

  Total iteration time breakdown (sec):
 Transport Sweeping:     2.309
 Inscatter Source  :     0.514
 Coarse-Mesh Accel :     5.796
 Else (Convergence):     0.714
 Total Time        :     9.333

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.78093E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 10/ 2018 at 11:32:27

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.97651   9.635E-05 1.933E-02 (    2, 41)   1.277E-01 ( 1769,  0) 11:32:29    1.9 s     1.9 s  95.5%    F
     2    0.97648   2.746E-05 4.219E-03 (    3, 45)   1.068E-03 (  338,  0) 11:32:31    3.8 s     1.9 s  95.0%    F
     3    0.97647   1.160E-05 1.664E-03 (    3, 45)   2.776E-04 ( 1949,  0) 11:32:33    5.6 s     1.8 s  87.5%    T
     4    0.97647   3.526E-06 7.504E-04 (    3, 44)   2.341E-04 (   80,  0) 11:32:35    7.6 s     2.0 s 100.0%    T
 k-eff =       0.97647017     Time=    255.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.611
 Inscatter Source  :     0.130
 Coarse-Mesh Accel :     1.693
 Else (Convergence):     0.182
 Total (per outer):      2.617

  Total iteration time breakdown (sec):
 Transport Sweeping:     2.446
 Inscatter Source  :     0.519
 Coarse-Mesh Accel :     6.773
 Else (Convergence):     0.729
 Total Time        :    10.467

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.76429E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 10/ 2018 at 11:33:10

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.97492   9.492E-05 1.886E-02 (    2, 41)   1.127E-01 (  985,  0) 11:33:12    1.9 s     1.9 s  97.0%    F
     2    0.97489   2.773E-05 4.187E-03 (    3, 45)   1.000E-03 ( 1905,  0) 11:33:14    3.7 s     1.7 s  87.0%    F
     3    0.97488   1.164E-05 1.642E-03 (    3, 45)   2.702E-04 (   80,  0) 11:33:15    5.4 s     1.8 s 176.0%    T
     4    0.97487   3.583E-06 7.406E-04 (    3, 44)   2.300E-04 ( 1949,  0) 11:33:17    7.4 s     1.9 s  96.0%    T
 k-eff =       0.97487421     Time=    285.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.622
 Inscatter Source  :     0.137
 Coarse-Mesh Accel :     1.559
 Else (Convergence):     0.191
 Total (per outer):      2.509

  Total iteration time breakdown (sec):
 Transport Sweeping:     2.487
 Inscatter Source  :     0.546
 Coarse-Mesh Accel :     6.238
 Else (Convergence):     0.764
 Total Time        :    10.035

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.74916E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 10/ 2018 at 11:33:50

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.97336   9.430E-05 1.773E-02 (    2, 41)   1.007E-01 (  985,  0) 11:33:52    2.1 s     2.1 s 103.5%    F
     2    0.97333   2.785E-05 4.149E-03 (    3, 45)   9.560E-04 ( 1905,  0) 11:33:54    4.0 s     1.9 s  95.0%    F
     3    0.97332   1.174E-05 1.619E-03 (    3, 45)   2.567E-04 ( 1949,  0) 11:33:56    6.0 s     2.0 s 101.5%    T
 k-eff =       0.97332061     Time=    315.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.665
 Inscatter Source  :     0.137
 Coarse-Mesh Accel :     1.806
 Else (Convergence):     0.237
 Total (per outer):      2.845

  Total iteration time breakdown (sec):
 Transport Sweeping:     1.996
 Inscatter Source  :     0.410
 Coarse-Mesh Accel :     5.417
 Else (Convergence):     0.711
 Total Time        :     8.534

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.73357E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 10/ 2018 at 11:34:31

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.97183   9.397E-05 1.770E-02 (    2, 41)   9.094E-02 ( 1769,  0) 11:34:34    3.1 s     3.1 s 104.3%    F
     2    0.97180   2.826E-05 4.238E-03 (    3, 45)   9.042E-04 (  338,  0) 11:34:36    5.3 s     2.2 s 109.0%    F
     3    0.97179   1.186E-05 1.670E-03 (    3, 45)   2.829E-04 (   80,  0) 11:34:38    7.4 s     2.1 s 106.5%    T
 k-eff =       0.97179307     Time=    345.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.870
 Inscatter Source  :     0.180
 Coarse-Mesh Accel :     2.348
 Else (Convergence):     0.320
 Total (per outer):      3.717

  Total iteration time breakdown (sec):
 Transport Sweeping:     2.611
 Inscatter Source  :     0.539
 Coarse-Mesh Accel :     7.043
 Else (Convergence):     0.959
 Total Time        :    11.152

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.71803E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 10/ 2018 at 11:35:11

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.97033   9.302E-05 1.708E-02 (    2, 41)   8.277E-02 (  985,  0) 11:35:14    2.1 s     2.1 s  71.3%    F
     2    0.97030   2.826E-05 4.201E-03 (    3, 45)   8.654E-04 ( 1905,  0) 11:35:16    4.2 s     2.1 s 104.5%    F
     3    0.97029   1.190E-05 1.654E-03 (    3, 45)   2.817E-04 (   80,  0) 11:35:18    6.2 s     1.9 s  97.0%    T
 k-eff =       0.97029154     Time=    375.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.681
 Inscatter Source  :     0.140
 Coarse-Mesh Accel :     1.949
 Else (Convergence):     0.311
 Total (per outer):      3.080

  Total iteration time breakdown (sec):
 Transport Sweeping:     2.042
 Inscatter Source  :     0.419
 Coarse-Mesh Accel :     5.846
 Else (Convergence):     0.932
 Total Time        :     9.239

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.70298E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
