SCALE Job started on Tue 29/05/2018 10:19:57
With Host name andrei2-HP-Notebook
working directory /tmp/scale.andrei2.18241
and process id 18241.
Input file named /home/andrei2/Desktop/ornl/msfr/scale/sandbox/triton1.inp
and output file named /home/andrei2/Desktop/ornl/msfr/scale/sandbox/triton1.out
##########################################################
>>> Loading SCALE Standard Composition Library from /home/andrei2/SCALE/SCALE-6.2.3/data/scale.rev39.sclib
>>> Loading CE library /home/andrei2/SCALE/SCALE-6.2.3/data/ce_v7.1_endf.xml
