SCALE Job started on Thu 12/07/2018 00:18:08
With Host name node20
working directory /home02/ybb/andreiRuns/msfr4/tmpdir
and process id 7172.
Input file named /home02/ybb/andreiRuns/msfr4/msfr_all_removal_and_th_feed.inp
and output file named /home02/ybb/andreiRuns/msfr4/msfr_all_removal_and_th_feed.out
##########################################################
***Created 1 infinite homogeneous cells from unreferenced mixtures.
***Warning: Nuclide 74180 is not contained in the specified library .
Attempting to use element 74000 failed. It is also not contained in the library
***Warning: 'Because nuclide 74180 is missing from the cross section library, its mixture 3 composition definition follows:
  b-10 3 0 3.92978e-05 973 end
  b-11 3 0 0.00014477 973 end
  c-12 3 0 0.00145833 973 end
  c-13 3 0 1.57729e-05 973 end
  al-27 3 0 0.000116061 973 end
  si-28 3 0 0.00049832 973 end
  si-29 3 0 2.53151e-05 973 end
  si-30 3 0 1.67074e-05 973 end
  p-31 3 0 4.47183e-05 973 end
  s-32 3 0 7.13609e-06 973 end
  s-33 3 0 5.63435e-08 973 end
  s-34 3 0 3.1928e-07 973 end
  s-36 3 0 7.51247e-10 973 end
  ti-46 3 0 3.06191e-05 973 end
  ti-47 3 0 2.76129e-05 973 end
  ti-48 3 0 0.000273605 973 end
  ti-49 3 0 2.00787e-05 973 end
  ti-50 3 0 1.92251e-05 973 end
  cr-50 3 0 0.000403291 973 end
  cr-52 3 0 0.00777707 973 end
  cr-53 3 0 0.000881858 973 end
  cr-54 3 0 0.000219513 973 end
  mn-55 3 0 0.000281716 973 end
  fe-54 3 0 3.98352e-05 973 end
  fe-56 3 0 0.000625328 973 end
  fe-57 3 0 1.44415e-05 973 end
  fe-58 3 0 1.9219e-06 973 end
  ni-58 3 0 0.0554827 973 end
  ni-60 3 0 0.0213718 973 end
  ni-61 3 0 0.000929018 973 end
  ni-62 3 0 0.00296212 973 end
  ni-64 3 0 0.000754364 973 end
  mo-92 3 0 6.82371e-05 973 end
  mo-94 3 0 4.26424e-05 973 end
  mo-95 3 0 7.34577e-05 973 end
  mo-96 3 0 7.70612e-05 973 end
  mo-97 3 0 4.4167e-05 973 end
  mo-98 3 0 0.000111757 973 end
  mo-100 3 0 4.46752e-05 973 end
  w-180 3 0 3.92143e-06 973 end
  w-182 3 0 0.000865982 973 end
  w-183 3 0 0.000467631 973 end
  w-184 3 0 0.00100127 973 end
  w-186 3 0 0.000929052 973 end
*** Warning - 1 issue(s) with the composition input resulting in removal of 1 nuclide(s) with a total of 3.92143e-06 atoms/barn-cm.
*** Mixture 3 density updated to 9.99883 grams/cc

*** If the default behavior is not acceptable, the above edits can be used to fix the composition input by removing or redistributing the atomic density of the missing nuclide(s).

*** This message can be suppressed by setting the environment variable MISSING_NUCLIDE_MSG_LEVEL=QUIET

*** The calculation will continue with the nuclide(s) removed, which will produce identical radiation transport and very similar activation/depletion results as using a cross section of 0.0 for each of the missing nuclide(s).

>>> Loading SCALE Standard Composition Library from /scale/scale_dev_data/scale.rev39.sclib
>>> Loading CE library /scale/release/6.2.2/linux/INSTALL/data/ce_v7.0_endf.xml
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 12/ 2018 at 00:27:10

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.97080   2.745E-02 4.303E+00 (    4,  1)   1.000E+00 (    1,  0) 00:27:42   32.0 s    32.0 s  99.9%    F
     2    0.97237   1.615E-03 3.843E+00 (    4,  1)   7.604E-01 (  630,  0) 00:28:05   55.6 s    23.6 s 102.8%    F
     3    0.97341   1.069E-03 3.692E+00 (    4,  1)   6.187E-02 (  599,  0) 00:28:24   74.1 s    18.5 s  97.2%    F
     4    0.97401   6.209E-04 3.475E+00 (    4,  1)   2.029E-02 (    1,  0) 00:28:48   98.0 s    23.9 s  99.8%    F
     5    0.97433   3.237E-04 3.270E+00 (    4,  1)   9.301E-03 (    1,  0) 00:29:13  123.3 s    25.3 s 101.1%    F
     6    0.97449   1.726E-04 3.077E+00 (    4,  1)   4.172E-03 (    1,  0) 00:29:37  147.3 s    24.0 s  99.9%    F
     7    0.97459   9.281E-05 2.904E+00 (    4,  1)   1.882E-03 (    1,  0) 00:30:00  170.0 s    22.8 s  99.0%    F
     8    0.97464   5.572E-05 2.758E+00 (    4,  1)   1.188E-03 (   49,  0) 00:30:25  195.6 s    25.6 s 102.3%    F
     9    0.97467   2.920E-05 2.639E+00 (    4,  1)   8.712E-04 (  816,  0) 00:30:54  224.5 s    28.9 s  99.7%    F
    10    0.97468   1.454E-05 2.544E+00 (    4,  1)   6.280E-04 (   49,  0) 00:31:24  254.6 s    30.0 s 100.1%    F
 k-eff =       0.97468218     Collapsing solution


  Time per Iteration (sec):
 Transport Sweeping:    11.604
 Inscatter Source  :     3.657
 Coarse-Mesh Accel :    17.441
 Else (Convergence):     0.815
 Total (per outer):     33.517

  Total iteration time breakdown (sec):
 Transport Sweeping:   116.035
 Inscatter Source  :    36.573
 Coarse-Mesh Accel :   174.414
 Else (Convergence):     8.146
 Total Time        :   335.168

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.74676E-01
 Equivalent core height is infinite.
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1019  for Nuclide:       94237
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1020  for Nuclide:       94237
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1019  for Nuclide:       94244
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1020  for Nuclide:       94244
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1019  for Nuclide:       96241
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1019  for Nuclide:       96248
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1020  for Nuclide:       96248
>>> Loading CE library /scale/release/6.2.2/linux/INSTALL/data/ce_v7.0_endf.xml
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 12/ 2018 at 00:37:04

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.99640   3.065E-02 4.784E-01 (    3, 49)   1.000E+00 (    1,  0) 00:37:10    6.0 s     6.0 s  99.8%    F
     2    0.99892   2.524E-03 4.008E-02 (    4, 13)   7.170E-01 (  630,  0) 00:37:14   10.7 s     4.7 s 117.3%    F
     3    1.00051   1.596E-03 2.386E-02 (    4, 13)   5.812E-02 (    1,  0) 00:37:19   15.1 s     4.4 s  88.8%    F
     4    1.00138   8.622E-04 1.430E-02 (    4, 14)   2.958E-02 (    1,  0) 00:37:23   18.8 s     3.7 s  92.5%    F
     5    1.00182   4.452E-04 8.403E-03 (    4, 14)   1.476E-02 (    1,  0) 00:37:26   21.9 s     3.1 s 103.3%    F
     6    1.00207   2.447E-04 5.054E-03 (    4, 14)   7.263E-03 (    1,  0) 00:37:29   25.0 s     3.1 s 104.3%    F
     7    1.00220   1.347E-04 3.230E-03 (    4, 16)   3.671E-03 (   49,  0) 00:37:32   28.2 s     3.2 s 105.7%    F
     8    1.00227   7.075E-05 2.371E-03 (    3, 18)   2.594E-03 (  816,  0) 00:37:35   31.5 s     3.3 s 110.3%    F
     9    1.00231   3.428E-05 2.001E-03 (    3, 18)   1.875E-03 (  816,  0) 00:37:39   34.9 s     3.4 s  84.3%    F
    10    1.00233   1.635E-05 1.658E-03 (    3, 22)   1.343E-03 (  816,  0) 00:37:42   38.3 s     3.4 s 113.3%    F
    11    1.00233   8.078E-06 1.340E-03 (    3, 22)   9.568E-04 (   49,  0) 00:37:46   41.7 s     3.4 s  85.2%    T
    12    1.00234   2.788E-06 1.073E-03 (    3, 22)   6.806E-04 (  816,  0) 00:37:49   45.2 s     3.5 s 115.0%    T
 k-eff =       1.00233644     Time=      0.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.696
 Inscatter Source  :     0.516
 Coarse-Mesh Accel :     1.044
 Else (Convergence):     0.150
 Total (per outer):      4.406

  Total iteration time breakdown (sec):
 Transport Sweeping:    32.353
 Inscatter Source  :     6.188
 Coarse-Mesh Accel :    12.532
 Else (Convergence):     1.800
 Total Time        :    52.873

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.00234E+00
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 12/ 2018 at 00:40:53

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.98503   3.179E-04 2.564E-02 (    3, 23)   1.867E-01 (  331,  0) 00:40:58    5.8 s     5.8 s 115.8%    F
     2    0.98507   4.332E-05 6.986E-03 (    4,  1)   5.456E-03 (  462,  0) 00:41:04   11.5 s     5.7 s  94.8%    F
     3    0.98510   3.183E-05 4.742E-03 (    3, 43)   3.926E-03 (  884,  0) 00:41:10   17.1 s     5.7 s  94.5%    F
     4    0.98512   2.149E-05 3.105E-03 (    3, 43)   7.771E-04 (  788,  0) 00:41:16   22.8 s     5.7 s  94.3%    F
     5    0.98514   1.265E-05 1.872E-03 (    3, 43)   3.546E-04 (  328,  0) 00:41:21   28.5 s     5.7 s 113.6%    T
 k-eff =       0.98513525     Time=     15.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.181
 Inscatter Source  :     0.502
 Coarse-Mesh Accel :     3.912
 Else (Convergence):     0.359
 Total (per outer):      6.954

  Total iteration time breakdown (sec):
 Transport Sweeping:    10.905
 Inscatter Source  :     2.512
 Coarse-Mesh Accel :    19.561
 Else (Convergence):     1.793
 Total Time        :    34.771

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.85135E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 12/ 2018 at 00:44:30

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.97504   3.974E-05 2.987E-02 (    3, 49)   5.374E-01 (  230,  0) 00:44:36    5.5 s     5.5 s  91.2%    F
     2    0.97504   5.208E-06 6.539E-03 (    3, 45)   3.091E-03 (  696,  0) 00:44:41   10.9 s     5.5 s 109.2%    F
     3    0.97504   3.104E-06 2.631E-03 (    3, 43)   8.883E-04 (  858,  0) 00:44:47   16.4 s     5.4 s  90.8%    F
     4    0.97504   1.280E-06 1.198E-03 (    3, 43)   1.367E-04 (  599,  0) 00:44:52   21.8 s     5.5 s 109.2%    T
 k-eff =       0.97503640     Time=     45.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.177
 Inscatter Source  :     0.529
 Coarse-Mesh Accel :     3.777
 Else (Convergence):     0.447
 Total (per outer):      6.930

  Total iteration time breakdown (sec):
 Transport Sweeping:     8.707
 Inscatter Source  :     2.117
 Coarse-Mesh Accel :    15.109
 Else (Convergence):     1.789
 Total Time        :    27.722

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.75006E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 12/ 2018 at 00:47:49

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.97006   7.649E-05 3.072E-02 (    3, 49)   4.333E-01 (  230,  0) 00:47:54    5.4 s     5.4 s 107.4%    F
     2    0.97004   2.461E-05 6.302E-03 (    3, 45)   2.326E-03 (  696,  0) 00:48:00   10.7 s     5.4 s  89.3%    F
     3    0.97003   1.371E-05 2.408E-03 (    3, 43)   4.805E-04 (  795,  0) 00:48:05   16.1 s     5.3 s 106.8%    F
     4    0.97002   5.791E-06 1.080E-03 (    3, 43)   1.488E-04 (  857,  0) 00:48:10   21.4 s     5.4 s 107.4%    T
 k-eff =       0.97002045     Time=     75.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.109
 Inscatter Source  :     0.506
 Coarse-Mesh Accel :     3.828
 Else (Convergence):     0.448
 Total (per outer):      6.892

  Total iteration time breakdown (sec):
 Transport Sweeping:     8.437
 Inscatter Source  :     2.025
 Coarse-Mesh Accel :    15.313
 Else (Convergence):     1.794
 Total Time        :    27.569

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.70022E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 12/ 2018 at 00:51:03

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.96740   9.113E-05 3.105E-02 (    3, 49)   3.275E-01 (  859,  0) 00:51:09    5.3 s     5.3 s  88.5%    F
     2    0.96736   3.768E-05 6.352E-03 (    3, 45)   1.765E-03 (  564,  0) 00:51:14   10.6 s     5.3 s 106.2%    F
     3    0.96735   1.817E-05 2.409E-03 (    3, 43)   3.889E-04 (  465,  0) 00:51:19   15.9 s     5.3 s 106.2%    F
     4    0.96734   7.619E-06 1.091E-03 (    3, 43)   1.970E-04 (  857,  0) 00:51:25   21.2 s     5.3 s  88.7%    T
 k-eff =       0.96733765     Time=    105.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.122
 Inscatter Source  :     0.479
 Coarse-Mesh Accel :     3.661
 Else (Convergence):     0.448
 Total (per outer):      6.710

  Total iteration time breakdown (sec):
 Transport Sweeping:     8.488
 Inscatter Source  :     1.918
 Coarse-Mesh Accel :    14.643
 Else (Convergence):     1.791
 Total Time        :    26.840

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.67333E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 12/ 2018 at 00:54:19

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.96587   9.584E-05 3.086E-02 (    3, 49)   2.554E-01 (  665,  0) 00:54:25    5.3 s     5.3 s  89.0%    F
     2    0.96583   4.298E-05 6.372E-03 (    3, 45)   1.372E-03 (  564,  0) 00:54:30   10.7 s     5.3 s 106.6%    F
     3    0.96581   1.993E-05 2.418E-03 (    3, 43)   3.598E-04 (  465,  0) 00:54:35   16.0 s     5.3 s 106.4%    F
     4    0.96580   8.374E-06 1.102E-03 (    3, 43)   2.173E-04 (  795,  0) 00:54:41   21.3 s     5.3 s  89.0%    T
 k-eff =       0.96579980     Time=    135.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.099
 Inscatter Source  :     0.505
 Coarse-Mesh Accel :     3.649
 Else (Convergence):     0.448
 Total (per outer):      6.701

  Total iteration time breakdown (sec):
 Transport Sweeping:     8.397
 Inscatter Source  :     2.020
 Coarse-Mesh Accel :    14.595
 Else (Convergence):     1.791
 Total Time        :    26.803

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.65819E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 12/ 2018 at 00:57:34

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.96487   9.859E-05 3.052E-02 (    3, 49)   2.064E-01 (  665,  0) 00:57:40    5.3 s     5.3 s  88.5%    F
     2    0.96482   4.556E-05 6.351E-03 (    3, 45)   1.127E-03 (  696,  0) 00:57:45   10.6 s     5.3 s 105.8%    F
     3    0.96480   2.077E-05 2.411E-03 (    3, 43)   3.386E-04 (  795,  0) 00:57:50   15.9 s     5.3 s 105.8%    F
     4    0.96479   8.731E-06 1.103E-03 (    3, 43)   2.213E-04 (  465,  0) 00:57:56   21.2 s     5.3 s  88.3%    T
 k-eff =       0.96479399     Time=    165.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.099
 Inscatter Source  :     0.479
 Coarse-Mesh Accel :     3.681
 Else (Convergence):     0.446
 Total (per outer):      6.706

  Total iteration time breakdown (sec):
 Transport Sweeping:     8.395
 Inscatter Source  :     1.918
 Coarse-Mesh Accel :    14.726
 Else (Convergence):     1.786
 Total Time        :    26.825

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.64799E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 12/ 2018 at 01:00:50

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.96410   9.988E-05 3.011E-02 (    3, 49)   1.719E-01 (  665,  0) 01:00:55    5.4 s     5.4 s 107.4%    F
     2    0.96406   4.664E-05 6.296E-03 (    3, 45)   9.606E-04 (  696,  0) 01:01:00   10.7 s     5.4 s 107.0%    F
     3    0.96404   2.109E-05 2.389E-03 (    3, 45)   3.257E-04 (  795,  0) 01:01:06   16.2 s     5.5 s  91.0%    F
 k-eff =       0.96403513     Time=    195.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.111
 Inscatter Source  :     0.518
 Coarse-Mesh Accel :     4.061
 Else (Convergence):     0.596
 Total (per outer):      7.286

  Total iteration time breakdown (sec):
 Transport Sweeping:     6.334
 Inscatter Source  :     1.554
 Coarse-Mesh Accel :    12.182
 Else (Convergence):     1.787
 Total Time        :    21.857

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.64061E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 12/ 2018 at 01:04:01

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.96350   1.006E-04 2.976E-02 (    3, 49)   1.466E-01 (  665,  0) 01:04:06    5.3 s     5.3 s 106.2%    F
     2    0.96345   4.832E-05 6.440E-03 (    3, 45)   8.628E-04 (  731,  0) 01:04:12   10.6 s     5.3 s  88.3%    F
     3    0.96343   2.170E-05 2.480E-03 (    3, 45)   3.463E-04 (  465,  0) 01:04:17   15.9 s     5.3 s 106.4%    F
 k-eff =       0.96342875     Time=    225.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.099
 Inscatter Source  :     0.474
 Coarse-Mesh Accel :     3.894
 Else (Convergence):     0.594
 Total (per outer):      7.060

  Total iteration time breakdown (sec):
 Transport Sweeping:     6.296
 Inscatter Source  :     1.421
 Coarse-Mesh Accel :    11.682
 Else (Convergence):     1.782
 Total Time        :    21.181

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.63425E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 12/ 2018 at 01:07:13

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.96296   1.001E-04 2.932E-02 (    3, 49)   1.274E-01 (  665,  0) 01:07:18    5.4 s     5.4 s 108.0%    F
     2    0.96292   4.839E-05 6.394E-03 (    3, 45)   8.967E-04 (  731,  0) 01:07:24   10.8 s     5.4 s  89.8%    F
     3    0.96290   2.170E-05 2.471E-03 (    3, 45)   3.469E-04 (  795,  0) 01:07:29   16.2 s     5.4 s 107.8%    F
 k-eff =       0.96289739     Time=    255.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.116
 Inscatter Source  :     0.510
 Coarse-Mesh Accel :     4.119
 Else (Convergence):     0.596
 Total (per outer):      7.340

  Total iteration time breakdown (sec):
 Transport Sweeping:     6.349
 Inscatter Source  :     1.529
 Coarse-Mesh Accel :    12.356
 Else (Convergence):     1.787
 Total Time        :    22.021

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.62909E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 12/ 2018 at 01:10:23

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.96248   9.895E-05 2.879E-02 (    3, 49)   1.123E-01 (  731,  0) 01:10:28    5.3 s     5.3 s 107.0%    F
     2    0.96243   4.798E-05 6.297E-03 (    3, 45)   9.087E-04 (  599,  0) 01:10:33   10.7 s     5.3 s 106.8%    F
     3    0.96241   2.151E-05 2.434E-03 (    3, 45)   3.431E-04 (  795,  0) 01:10:39   16.0 s     5.3 s  89.0%    F
 k-eff =       0.96240862     Time=    285.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.115
 Inscatter Source  :     0.479
 Coarse-Mesh Accel :     4.118
 Else (Convergence):     0.596
 Total (per outer):      7.307

  Total iteration time breakdown (sec):
 Transport Sweeping:     6.344
 Inscatter Source  :     1.437
 Coarse-Mesh Accel :    12.353
 Else (Convergence):     1.787
 Total Time        :    21.921

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.62407E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 12/ 2018 at 01:13:33

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.96231   8.129E-05 2.851E-02 (    3, 49)   9.998E-02 (  731,  0) 01:13:38    5.4 s     5.4 s 107.2%    F
     2    0.96227   4.378E-05 6.246E-03 (    3, 45)   8.170E-04 (  731,  0) 01:13:44   10.7 s     5.4 s  89.3%    F
     3    0.96225   2.052E-05 2.392E-03 (    3, 45)   3.351E-04 (  465,  0) 01:13:49   16.1 s     5.4 s 107.6%    F
 k-eff =       0.96224770     Time=    315.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.111
 Inscatter Source  :     0.505
 Coarse-Mesh Accel :     4.185
 Else (Convergence):     0.595
 Total (per outer):      7.396

  Total iteration time breakdown (sec):
 Transport Sweeping:     6.334
 Inscatter Source  :     1.514
 Coarse-Mesh Accel :    12.554
 Else (Convergence):     1.785
 Total Time        :    22.187

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.62294E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 12/ 2018 at 01:16:42

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.96189   9.621E-05 2.772E-02 (    3, 49)   9.047E-02 (  599,  0) 01:16:47    5.3 s     5.3 s 106.0%    F
     2    0.96185   4.708E-05 6.062E-03 (    3, 45)   8.726E-04 (  599,  0) 01:16:52   10.6 s     5.3 s 106.0%    F
     3    0.96183   2.121E-05 2.334E-03 (    3, 45)   3.149E-04 (  795,  0) 01:16:58   15.9 s     5.3 s  88.5%    F
 k-eff =       0.96182915     Time=    345.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.099
 Inscatter Source  :     0.472
 Coarse-Mesh Accel :     4.101
 Else (Convergence):     0.595
 Total (per outer):      7.267

  Total iteration time breakdown (sec):
 Transport Sweeping:     6.298
 Inscatter Source  :     1.417
 Coarse-Mesh Accel :    12.302
 Else (Convergence):     1.784
 Total Time        :    21.801

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.61815E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 12/ 2018 at 01:19:51

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.96149   9.527E-05 2.724E-02 (    3, 49)   8.229E-02 (  731,  0) 01:19:56    5.3 s     5.3 s 106.6%    F
     2    0.96145   4.653E-05 5.959E-03 (    3, 45)   8.634E-04 (  731,  0) 01:20:01   10.6 s     5.3 s 106.2%    F
     3    0.96143   2.093E-05 2.294E-03 (    3, 45)   3.105E-04 (  465,  0) 01:20:07   16.0 s     5.3 s  88.8%    F
 k-eff =       0.96142741     Time=    375.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.110
 Inscatter Source  :     0.478
 Coarse-Mesh Accel :     4.112
 Else (Convergence):     0.593
 Total (per outer):      7.294

  Total iteration time breakdown (sec):
 Transport Sweeping:     6.329
 Inscatter Source  :     1.435
 Coarse-Mesh Accel :    12.337
 Else (Convergence):     1.780
 Total Time        :    21.881

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.61423E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 12/ 2018 at 01:23:00

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.96109   9.480E-05 2.666E-02 (    3, 49)   7.537E-02 (  731,  0) 01:23:06    5.3 s     5.3 s  89.0%    F
     2    0.96104   4.613E-05 5.830E-03 (    3, 45)   8.493E-04 (  731,  0) 01:23:11   10.7 s     5.3 s 106.8%    F
     3    0.96102   2.073E-05 2.242E-03 (    3, 45)   3.017E-04 (  465,  0) 01:23:16   16.0 s     5.4 s 107.0%    F
 k-eff =       0.96102419     Time=    405.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.113
 Inscatter Source  :     0.478
 Coarse-Mesh Accel :     3.999
 Else (Convergence):     0.597
 Total (per outer):      7.188

  Total iteration time breakdown (sec):
 Transport Sweeping:     6.340
 Inscatter Source  :     1.435
 Coarse-Mesh Accel :    11.998
 Else (Convergence):     1.792
 Total Time        :    21.565

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.61031E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 12/ 2018 at 01:26:11

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.96071   9.280E-05 2.618E-02 (    3, 49)   6.944E-02 (  731,  0) 01:26:16    5.3 s     5.3 s 106.8%    F
     2    0.96067   4.530E-05 5.705E-03 (    3, 45)   8.284E-04 (  731,  0) 01:26:22   10.7 s     5.3 s  88.7%    F
     3    0.96065   2.039E-05 2.187E-03 (    3, 45)   2.925E-04 (  795,  0) 01:26:27   16.0 s     5.4 s 107.0%    F
 k-eff =       0.96064981     Time=    435.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.107
 Inscatter Source  :     0.478
 Coarse-Mesh Accel :     4.162
 Else (Convergence):     0.597
 Total (per outer):      7.343

  Total iteration time breakdown (sec):
 Transport Sweeping:     6.320
 Inscatter Source  :     1.433
 Coarse-Mesh Accel :    12.485
 Else (Convergence):     1.790
 Total Time        :    22.028

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.60606E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 12/ 2018 at 01:29:16

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.96037   9.160E-05 2.565E-02 (    3, 49)   6.433E-02 (  731,  0) 01:29:21    5.3 s     5.3 s 106.6%    F
     2    0.96032   4.482E-05 5.582E-03 (    3, 45)   8.118E-04 (  731,  0) 01:29:26   10.6 s     5.3 s 106.2%    F
     3    0.96030   2.019E-05 2.136E-03 (    3, 45)   2.842E-04 (  465,  0) 01:29:32   16.0 s     5.3 s  89.0%    F
 k-eff =       0.96030361     Time=    465.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.112
 Inscatter Source  :     0.477
 Coarse-Mesh Accel :     4.112
 Else (Convergence):     0.594
 Total (per outer):      7.295

  Total iteration time breakdown (sec):
 Transport Sweeping:     6.337
 Inscatter Source  :     1.431
 Coarse-Mesh Accel :    12.335
 Else (Convergence):     1.781
 Total Time        :    21.884

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.60311E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
 ===================================================================================================================================
   Outer iteration sweep begins 07/ 12/ 2018 at 01:32:21

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.96004   9.035E-05 2.516E-02 (    3, 49)   5.986E-02 (  731,  0) 01:32:26    5.3 s     5.3 s 106.6%    F
     2    0.95999   4.424E-05 5.460E-03 (    3, 45)   7.951E-04 (  731,  0) 01:32:31   10.6 s     5.3 s 106.4%    F
     3    0.95998   1.994E-05 2.085E-03 (    3, 45)   2.761E-04 (  795,  0) 01:32:37   16.0 s     5.3 s  88.8%    T
 k-eff =       0.95997521     Time=    495.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.108
 Inscatter Source  :     0.482
 Coarse-Mesh Accel :     4.074
 Else (Convergence):     0.594
 Total (per outer):      7.258

  Total iteration time breakdown (sec):
 Transport Sweeping:     6.325
 Inscatter Source  :     1.446
 Coarse-Mesh Accel :    12.223
 Else (Convergence):     1.781
 Total Time        :    21.775

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.59951E-01
 Equivalent core height is infinite.
