SCALE Job started on Fri 27/07/2018 15:41:31
With Host name andrei2-HP-Notebook
working directory /tmp/scale.andrei2.28106
and process id 28106.
Input file named /home/andrei2/Desktop/ornl/mcsfr/scale/no_reproc_depl/510efpd_w_vol/quarter_cell.inp
and output file named /home/andrei2/Desktop/ornl/mcsfr/scale/no_reproc_depl/510efpd_w_vol/quarter_cell.out
##########################################################
***Error:        Geometry input text "" does not match recognized keyword.  Input cannot be processed.
