SCALE Job started on Wed 01/08/2018 15:44:59
With Host name andrei2-HP-Notebook
working directory /tmp/scale.andrei2.20076
and process id 20076.
Input file named /home/andrei2/Desktop/ornl/mcsfr/scale/no_reproc_depl/510efpd_w_vol/quarter_cell.inp
and output file named /home/andrei2/Desktop/ornl/mcsfr/scale/no_reproc_depl/510efpd_w_vol/quarter_cell.out
##########################################################
>>> Loading SCALE Standard Composition Library from /home/andrei2/SCALE/SCALE-6.2.3/data/scale.rev39.sclib
>>> Loading CE library /home/andrei2/SCALE/SCALE-6.2.3/data/ce_v7.0_endf.xml
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 01/ 2018 at 15:48:48

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.98567   2.652E-02 7.654E+00 (    3,137)   1.000E+00 (    1,  0) 15:48:48    0.5 s     0.5 s  52.0%    F
     2    0.98465   1.039E-03 2.161E-01 (    2,193)   7.923E-01 (  287,  0) 15:48:49    1.0 s     0.5 s  53.0%    F
     3    0.98490   2.525E-04 1.211E-01 (    4,228)   9.895E-02 (    2,  0) 15:48:50    1.6 s     0.5 s  54.0%    F
     4    0.98518   2.891E-04 1.160E-01 (    4,228)   3.496E-02 (    6,  0) 15:48:50    2.2 s     0.6 s  58.0%    F
     5    0.98538   2.014E-04 2.442E-02 (    4,228)   1.588E-02 (  249,  0) 15:48:51    2.7 s     0.5 s  55.0%    F
     6    0.98553   1.481E-04 1.075E-02 (    3,146)   1.233E-02 (  249,  0) 15:48:51    3.3 s     0.6 s  59.0%    F
     7    0.98563   1.017E-04 6.962E-03 (    3,146)   1.004E-02 (  287,  0) 15:48:52    3.8 s     0.5 s  53.0%    F
     8    0.98572   9.146E-05 4.539E-03 (    3,146)   8.516E-03 (  287,  0) 15:48:52    4.4 s     0.5 s  53.0%    F
     9    0.98580   8.471E-05 2.855E-03 (    3,146)   7.135E-03 (  287,  0) 15:48:53    5.0 s     0.6 s  59.0%    F
    10    0.98586   5.766E-05 1.831E-03 (    3,146)   5.956E-03 (  287,  0) 15:48:54    5.6 s     0.6 s  59.0%    F
    11    0.98590   4.586E-05 1.429E-03 (    3, 58)   4.988E-03 (  287,  0) 15:48:54    6.2 s     0.6 s  63.0%    F
    12    0.98594   3.454E-05 1.116E-03 (    3, 58)   4.166E-03 (  287,  0) 15:48:55    6.8 s     0.6 s  63.0%    F
    13    0.98596   2.504E-05 8.640E-04 (    3, 58)   3.477E-03 (  287,  0) 15:48:55    7.5 s     0.7 s  66.0%    F
    14    0.98598   2.052E-05 7.805E-04 (    4,228)   2.906E-03 (  287,  0) 15:48:56    8.2 s     0.7 s  70.0%    F
    15    0.98600   1.620E-05 6.458E-04 (    4,228)   2.418E-03 (  287,  0) 15:48:57    8.9 s     0.7 s  69.0%    F
    16    0.98601   1.300E-05 5.535E-04 (    4,228)   2.012E-03 (  287,  0) 15:48:58    9.6 s     0.7 s  70.0%    F
    17    0.98602   1.041E-05 4.670E-04 (    4,228)   1.671E-03 (  287,  0) 15:48:58   10.2 s     0.7 s  69.0%    F
    18    0.98603   8.442E-06 3.957E-04 (    4,228)   1.387E-03 (  287,  0) 15:48:59   11.0 s     0.7 s  72.0%    F
    19    0.98603   6.915E-06 3.443E-04 (    4,228)   1.149E-03 (  287,  0) 15:49:00   11.6 s     0.7 s  68.0%    F
    20    0.98604   5.464E-06 2.792E-04 (    4,228)   9.512E-04 (  287,  0) 15:49:00   12.3 s     0.6 s  64.0%    F
    21    0.98604   4.471E-06 2.397E-04 (    4,228)   7.894E-04 (  269,  0) 15:49:01   12.9 s     0.7 s  66.0%    F
 k-eff =       0.98604406     Collapsing solution


  Time per Iteration (sec):
 Transport Sweeping:     0.341
 Inscatter Source  :     0.061
 Coarse-Mesh Accel :     0.327
 Else (Convergence):     0.024
 Total (per outer):      0.754

  Total iteration time breakdown (sec):
 Transport Sweeping:     7.169
 Inscatter Source  :     1.275
 Coarse-Mesh Accel :     6.869
 Else (Convergence):     0.514
 Total Time        :    15.827

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.86046E-01
 Equivalent core height is infinite.
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1019  for Nuclide:       94237
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1020  for Nuclide:       94237
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1019  for Nuclide:       94244
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1020  for Nuclide:       94244
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1019  for Nuclide:       96241
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1019  for Nuclide:       96248
***Error:  Unable to get Nu*Sigmaf corresponding to MT:        1020  for Nuclide:       96248
>>> Loading CE library /home/andrei2/SCALE/SCALE-6.2.3/data/ce_v7.0_endf.xml
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 01/ 2018 at 15:52:48

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.99373   3.110E-02 6.543E-01 (    2, 37)   1.000E+00 (    1,  0) 15:52:49    0.1 s     0.1 s  11.0%    F
     2    0.99361   1.203E-04 1.042E-01 (    3, 20)   7.955E-01 (  287,  0) 15:52:49    0.2 s     0.1 s   9.0%    F
     3    0.99429   6.767E-04 3.707E-02 (    3, 20)   9.465E-02 (    4,  0) 15:52:49    0.3 s     0.1 s   9.0%    F
     4    0.99487   5.821E-04 2.089E-02 (    3, 22)   3.659E-02 (    6,  0) 15:52:49    0.4 s     0.1 s   9.0%    F
     5    0.99527   4.070E-04 1.481E-02 (    2, 22)   1.869E-02 (  287,  0) 15:52:49    0.5 s     0.1 s  10.0%    F
     6    0.99554   2.686E-04 1.042E-02 (    2, 22)   1.432E-02 (  287,  0) 15:52:49    0.6 s     0.1 s   9.0%    F
     7    0.99572   1.810E-04 7.454E-03 (    3, 22)   1.127E-02 (  287,  0) 15:52:49    0.7 s     0.1 s  11.0%    F
     8    0.99587   1.488E-04 5.351E-03 (    3, 22)   9.037E-03 (  287,  0) 15:52:49    0.8 s     0.1 s  10.0%    F
     9    0.99596   9.741E-05 3.884E-03 (    3, 22)   7.356E-03 (  287,  0) 15:52:49    0.9 s     0.1 s   9.0%    F
    10    0.99603   7.040E-05 2.850E-03 (    3, 22)   6.036E-03 (  287,  0) 15:52:49    1.0 s     0.1 s  10.0%    F
    11    0.99608   4.907E-05 2.110E-03 (    3, 22)   5.019E-03 (  287,  0) 15:52:50    1.1 s     0.1 s  11.0%    F
    12    0.99612   3.537E-05 1.569E-03 (    3, 22)   4.203E-03 (  287,  0) 15:52:50    1.2 s     0.1 s  12.0%    F
    13    0.99614   2.602E-05 1.163E-03 (    3, 22)   3.540E-03 (  287,  0) 15:52:50    1.3 s     0.1 s   9.0%    F
    14    0.99616   2.025E-05 8.641E-04 (    3, 22)   2.987E-03 (  287,  0) 15:52:50    1.4 s     0.1 s  10.0%    F
    15    0.99618   1.562E-05 6.422E-04 (    3, 22)   2.530E-03 (  287,  0) 15:52:50    1.5 s     0.1 s   9.0%    F
    16    0.99619   1.200E-05 4.761E-04 (    3, 22)   2.159E-03 (  269,  0) 15:52:50    1.6 s     0.1 s  10.0%    F
    17    0.99620   1.010E-05 3.784E-04 (    4, 47)   1.849E-03 (  286,  0) 15:52:50    1.7 s     0.1 s  10.0%    F
    18    0.99621   7.601E-06 3.070E-04 (    4, 49)   1.583E-03 (  269,  0) 15:52:50    1.8 s     0.1 s  10.0%    F
    19    0.99621   6.327E-06 2.793E-04 (    4, 48)   1.358E-03 (  286,  0) 15:52:50    1.9 s     0.1 s   9.0%    F
    20    0.99622   5.236E-06 2.398E-04 (    4, 48)   1.163E-03 (  269,  0) 15:52:50    2.0 s     0.1 s  10.0%    F
    21    0.99622   4.365E-06 2.102E-04 (    4, 47)   9.962E-04 (  269,  0) 15:52:51    2.1 s     0.1 s  10.0%    F
    22    0.99623   3.421E-06 1.750E-04 (    4, 48)   8.527E-04 (  286,  0) 15:52:51    2.2 s     0.1 s  10.0%    F
 k-eff =       0.99622787     Time=      0.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.078
 Inscatter Source  :     0.010
 Coarse-Mesh Accel :     0.055
 Else (Convergence):     0.005
 Total (per outer):      0.148

  Total iteration time breakdown (sec):
 Transport Sweeping:     1.714
 Inscatter Source  :     0.222
 Coarse-Mesh Accel :     1.203
 Else (Convergence):     0.112
 Total Time        :     3.251

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.96215E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 01/ 2018 at 15:53:23

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.99480   5.104E-04 4.299E-01 (    3, 35)   3.306E-01 (  279,  0) 15:53:23    0.1 s     0.1 s  14.0%    F
     2    0.99461   1.930E-04 2.348E-02 (    2, 40)   1.167E-02 (  193,  0) 15:53:23    0.3 s     0.1 s  14.0%    F
     3    0.99453   7.464E-05 5.477E-03 (    2, 43)   2.071E-03 (    2,  0) 15:53:23    0.4 s     0.1 s  13.0%    F
     4    0.99450   3.229E-05 1.668E-03 (    2, 44)   9.830E-04 (  108,  0) 15:53:23    0.6 s     0.1 s  14.0%    F
     5    0.99448   1.582E-05 5.322E-04 (    3, 43)   6.095E-04 (   19,  0) 15:53:23    0.7 s     0.1 s  13.0%    F
 k-eff =       0.99448369     Time=    127.50d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.074
 Inscatter Source  :     0.011
 Coarse-Mesh Accel :     0.067
 Else (Convergence):     0.023
 Total (per outer):      0.175

  Total iteration time breakdown (sec):
 Transport Sweeping:     0.368
 Inscatter Source  :     0.057
 Coarse-Mesh Accel :     0.336
 Else (Convergence):     0.115
 Total Time        :     0.876

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.94474E-01
 Equivalent core height is infinite.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:24.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:33.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:32.
Normalize 2D Cross Sections: There are no groups in scatter matrix Legendre order:0 for MT:41.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 01/ 2018 at 15:53:59

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    0.99145   1.029E-03 4.556E-01 (    3, 35)   3.653E-01 (  160,  0) 15:53:59    0.2 s     0.2 s  15.0%    F
     2    0.99108   3.766E-04 1.233E-02 (    3, 33)   1.472E-02 (  123,  0) 15:53:59    0.3 s     0.1 s  13.0%    F
     3    0.99094   1.410E-04 2.543E-03 (    2, 20)   3.145E-03 (  230,  0) 15:54:00    0.4 s     0.1 s  14.0%    F
     4    0.99088   5.963E-05 1.159E-03 (    2, 20)   1.329E-03 (  230,  0) 15:54:00    0.6 s     0.2 s  15.0%    F
     5    0.99085   2.926E-05 6.548E-04 (    2, 20)   7.814E-04 (    3,  0) 15:54:00    0.7 s     0.2 s  15.0%    F
     6    0.99084   1.604E-05 4.232E-04 (    2, 20)   5.715E-04 (    3,  0) 15:54:00    0.9 s     0.2 s  16.0%    F
 k-eff =       0.99083543     Time=    382.50d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     0.079
 Inscatter Source  :     0.011
 Coarse-Mesh Accel :     0.150
 Else (Convergence):     0.019
 Total (per outer):      0.259

  Total iteration time breakdown (sec):
 Transport Sweeping:     0.476
 Inscatter Source  :     0.066
 Coarse-Mesh Accel :     0.897
 Else (Convergence):     0.114
 Total Time        :     1.553

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  9.90820E-01
 Equivalent core height is infinite.
