SCALE Job started on Mon 30/07/2018 08:34:26
With Host name andrei2-HP-Notebook
working directory /tmp/scale.andrei2.12634
and process id 12634.
Input file named /home/andrei2/Desktop/ornl/mcsfr/scale/no_reproc_depl/4080efd/mcsfr_opus_after.inp
and output file named /home/andrei2/Desktop/ornl/mcsfr/scale/no_reproc_depl/4080efd/mcsfr_opus_after.out
##########################################################
cp /home/andrei2/Desktop/ornl/mcsfr/scale/no_reproc_depl/4080efd/mcsfr_no_move_4080d.f71 f71
