SCALE Job started on Mon 11/06/2018 13:05:08
With Host name andrei2-HP-Notebook
working directory /tmp/scale.andrei2.30855
and process id 30855.
Input file named /home/andrei2/Desktop/ornl/mcsfr/scale/quarter_cell.inp
and output file named /home/andrei2/Desktop/ornl/mcsfr/scale/quarter_cell.out
##########################################################
>>> Loading SCALE Standard Composition Library from /home/andrei2/SCALE/SCALE-6.2.3/data/scale.rev39.sclib
>>> Loading CE library /home/andrei2/SCALE/SCALE-6.2.3/data/ce_v7.0_endf.xml
 ===================================================================================================================================
   Outer iteration sweep begins 06/ 11/ 2018 at 13:05:35

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.00268   6.732E-03 4.338E+00 (    3,137)   1.000E+00 (    1,  0) 13:05:39    3.7 s     3.7 s  91.2%    F
     2    1.00130   1.383E-03 1.643E-01 (    4,  1)   2.847E-01 (  938,  0) 13:05:42    7.1 s     3.4 s 114.0%    F
     3    1.00140   9.564E-05 3.870E-02 (    4,  9)   1.129E-01 (    4,  0) 13:05:46   10.3 s     3.2 s  81.2%    F
     4    1.00146   6.511E-05 2.722E-02 (    3,228)   2.061E-02 (  203,  0) 13:05:49   14.1 s     3.8 s 127.0%    F
     5    1.00144   1.748E-05 5.399E-03 (    3, 56)   4.495E-03 (    4,  0) 13:05:54   18.6 s     4.5 s  89.8%    F
     6    1.00137   6.870E-05 3.185E-03 (    3, 57)   1.506E-03 (  885,  0) 13:05:58   23.1 s     4.4 s 111.2%    F
     7    1.00115   2.209E-04 2.523E-03 (    2, 73)   7.476E-04 ( 1090,  0) 13:06:04   29.3 s     6.2 s 103.8%    F
     8    1.00092   2.330E-04 1.246E-03 (    4, 63)   5.143E-04 (  305,  0) 13:06:11   36.2 s     7.0 s  99.3%    F
 k-eff =       1.00091998     


  Time per Iteration (sec):
 Transport Sweeping:     2.433
 Inscatter Source  :     0.394
 Coarse-Mesh Accel :     2.694
 Else (Convergence):     0.490
 Total (per outer):      6.011

  Total iteration time breakdown (sec):
 Transport Sweeping:    19.467
 Inscatter Source  :     3.149
 Coarse-Mesh Accel :    21.552
 Else (Convergence):     3.921
 Total Time        :    48.089

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.00077E+00
 Equivalent core height is infinite.
The number of cross section groups is 0, but the number of flux groups is 238 in Malocs.
